Repository mlpack/mlpack, pull requests merged in 2019-06, with the labels that each got.

#1901 Multiple Pole Balancing Environment
  HISTORY.md
  src/mlpack/methods/reinforcement_learning/environment/CMakeLists.txt
  src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp
  src/mlpack/methods/reinforcement_learning/environment/continuous_multiple_pole_cart.hpp
  src/mlpack/methods/reinforcement_learning/environment/multiple_pole_cart.hpp
  src/mlpack/tests/rl_components_test.cpp
Labels: c: methods, c: testing, t: added feature

#1917 bump version to 3.1.1
  Doxyfile
Labels: s: needs review, s: unanswered, s: unlabeled

#1921 Random forest test stability fixes
  src/mlpack/tests/main_tests/random_forest_test.cpp
Labels: c: testing, t: bugfix

#1922 Resolve calculation of accuracy
  src/mlpack/methods/softmax_regression/softmax_regression_main.cpp
Labels: c: methods, s: needs review, t: bugfix

#1925 Code of Conduct.
  CODE_OF_CONDUCT.md
Labels: c: documentation

#1930 Add linear layer in model for numerical gradient tests
  src/mlpack/methods/ann/layer/batch_norm.hpp
  src/mlpack/methods/ann/layer/batch_norm_impl.hpp
  src/mlpack/methods/ann/layer/layer_norm.hpp
  src/mlpack/methods/ann/layer/layer_norm_impl.hpp
  src/mlpack/tests/ann_layer_test.cpp
Labels: c: testing, t: bugfix

#1943 Minor Optimisation in Backward computation
  src/mlpack/methods/ann/layer/batch_norm_impl.hpp
  src/mlpack/methods/ann/layer/layer_norm_impl.hpp
Labels: c: methods, t: added feature
