Repository mlpack/mlpack, pull requests merged in 2019-05, with the labels that each got.

#1890 Change of Version in Readme
  README.md
Labels: c: documentation, t: bugfix

#1843 Implemetation of Concatenated ReLU Activation
  src/mlpack/methods/ann/layer/CMakeLists.txt
  src/mlpack/methods/ann/layer/c_relu.hpp
  src/mlpack/methods/ann/layer/c_relu_impl.hpp
  src/mlpack/methods/ann/layer/layer_types.hpp
  src/mlpack/tests/activation_functions_test.cpp
Labels: c: methods, s: needs review, t: added feature

#1893 Refactor Windows Build Tutorial
  doc/guide/build_windows.hpp
Labels: c: documentation, s: needs review, s: unanswered, t: added feature

#1829 Added support for concat along an axis.
  src/mlpack/methods/ann/layer/concat.hpp
  src/mlpack/methods/ann/layer/concat_impl.hpp
  src/mlpack/tests/ann_layer_test.cpp
Labels: c: methods, s: needs review, t: added feature

#1882 Option inconsistency in perceptron
  HISTORY.md
  src/mlpack/methods/adaboost/adaboost_main.cpp
  src/mlpack/methods/perceptron/perceptron_main.cpp
  src/mlpack/tests/main_tests/adaboost_test.cpp
  src/mlpack/tests/main_tests/perceptron_test.cpp
Labels: c: documentation, s: needs review, s: unanswered

#1897 Concat layer minor style fixes.
  src/mlpack/bindings/markdown/binding_info.hpp
  src/mlpack/methods/ann/layer/concat.hpp
  src/mlpack/methods/ann/layer/concat_impl.hpp
Labels: c: documentation, c: methods

#1898 Python spacing fix
  doc/guide/python_quickstart.hpp
  src/mlpack/bindings/python/print_input_processing.hpp
  src/mlpack/bindings/python/tests/test_python_binding.py
  src/mlpack/bindings/python/tests/test_python_binding_main.cpp
  src/mlpack/core/util/param.hpp
Labels: c: automatic bindings, s: needs review, s: unanswered, t: bugfix

#1900 Install ensmallen headers when downloaded during build.
  CMakeLists.txt
  HISTORY.md
Labels: c: build system, t: bugfix

#1813 Fix O'Reilly GAN Test
  src/mlpack/tests/dcgan_test.cpp
  src/mlpack/tests/gan_test.cpp
Labels: c: methods, t: bugfix

#1902 Make random forest tests more robust
  src/mlpack/tests/random_forest_test.cpp
Labels: c: testing

#1823 Introduce Memory Sharing Between GAN and FFN
  src/mlpack/methods/ann/gan/gan.hpp
  src/mlpack/methods/ann/gan/gan_impl.hpp
  src/mlpack/methods/ann/gan/wgan_impl.hpp
  src/mlpack/methods/ann/gan/wgangp_impl.hpp
  src/mlpack/tests/gan_test.cpp
Labels: c: methods, s: needs review, t: bugfix

#1907 Fix link to 'getting involved'
  CONTRIBUTING.md
Labels: c: documentation, t: bug report

#1905 Fix serialization of glimpse, maxPooling and meanPooling layers.
  src/mlpack/methods/ann/layer/glimpse_impl.hpp
  src/mlpack/methods/ann/layer/max_pooling_impl.hpp
  src/mlpack/methods/ann/layer/mean_pooling_impl.hpp
Labels: c: methods, t: bugfix
