Repository mlpack/mlpack, pull requests merged in 2019-11, with the labels that each got.

#2065 Reference a version number in the STB directory
  CMakeLists.txt
Labels: c: build system

#2074 Extending callbacks to NCA and LMNN
  src/mlpack/methods/lmnn/lmnn.hpp
  src/mlpack/methods/lmnn/lmnn_impl.hpp
  src/mlpack/methods/nca/nca.hpp
  src/mlpack/methods/nca/nca_impl.hpp
  src/mlpack/tests/callback_test.cpp
Labels: c: methods, t: added feature

#2076 Pointing to ensmallend docs for callbacks docs
  src/mlpack/methods/ann/ffn.hpp
  src/mlpack/methods/ann/gan/gan.hpp
  src/mlpack/methods/ann/rnn.hpp
  src/mlpack/methods/logistic_regression/logistic_regression.hpp
Labels: c: methods, s: needs review, t: added feature

#2068 Governance guidelines
  GOVERNANCE.md
Labels: c: documentation, t: added feature

#2079 Fix memory handling issues of RangeSearch and NeighborSearch.
  src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
  src/mlpack/methods/range_search/range_search_impl.hpp
Labels: c: methods, t: bugfix

#2080 Update LSTM documentation to indicate need for IdentityLayer
  src/mlpack/methods/ann/layer/fast_lstm.hpp
  src/mlpack/methods/ann/layer/lstm.hpp
Labels: c: documentation, c: methods, t: added feature

#2083 GitHub + NumFOCUS Sponsor button.
  .github/FUNDING.yml
Labels: s: needs review

#1988 Valid and Same padding option in convolution layers.
  HISTORY.md
  src/mlpack/methods/ann/layer/atrous_convolution.hpp
  src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
  src/mlpack/methods/ann/layer/convolution.hpp
  src/mlpack/methods/ann/layer/convolution_impl.hpp
  src/mlpack/tests/ann_layer_test.cpp
Labels: c: methods, s: needs review, t: added feature

#2085 Cleanups for `core/arma_extend/`
  src/mlpack/core/arma_extend/CMakeLists.txt
  src/mlpack/core/arma_extend/arma_extend.hpp
  src/mlpack/core/arma_extend/fn_inplace_reshape.hpp
  src/mlpack/core/arma_extend/hdf5_misc.hpp
  src/mlpack/tests/arma_extend_test.cpp
Labels: c: core

#2058 Azure pipelines
  .ci/ci.yaml
  .ci/linux-steps.yaml
  .ci/macos-steps.yaml
  .ci/windows-steps.yaml
Labels: c: build system, c: testing, s: needs review, t: added feature

#2093 Add attribution for NumFOCUS to README.md
  README.md
Labels: c: documentation, s: needs review

#2090 unset BOOST_ROOT (azure pipelines)
  .ci/ci.yaml
  .ci/linux-steps.yaml
  src/mlpack/methods/ann/layer/layer_types.hpp
  src/mlpack/tests/CMakeLists.txt
Labels: c: build system, s: needs review, t: bugfix

#2095 Show the latest mlpack release (3.2.2) in Readme.md
  README.md
Labels: c: documentation, s: needs review

#2094 Fix coverage build by linking against quadmath
  CMakeLists.txt
Labels: c: build system, t: bugfix

#2098 Handle paths with spaces in coverage script
  CMake/mlpack_coverage.in
Labels: c: build system, c: testing, t: bugfix
