Repository mlpack/mlpack, pull requests merged in 2019-07, with the labels that each got.

#1941 Made continuous RL environments' API consistent
  HISTORY.md
  src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp
  src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp
  src/mlpack/methods/reinforcement_learning/environment/continuous_mountain_car.hpp
  src/mlpack/methods/reinforcement_learning/environment/continuous_multiple_pole_cart.hpp
  src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
  src/mlpack/methods/reinforcement_learning/environment/multiple_pole_cart.hpp
  src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
  src/mlpack/methods/reinforcement_learning/environment/reward_clipping.hpp
  src/mlpack/tests/rl_components_test.cpp
Labels: c: methods, s: needs review, t: added feature

#1947 Fix CI-Travis Build
  src/mlpack/bindings/python/setup.py.in
Labels: c: build system, s: needs review, t: bugfix

#1945 Fix PyPI documentation error.
  doc/guide/python_quickstart.hpp
Labels: c: automatic bindings, c: documentation, t: bugfix

#1899 Add GMM test for command-line and python bindings
  src/mlpack/methods/gmm/gmm_train_main.cpp
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/main_tests/gmm_generate_test.cpp
  src/mlpack/tests/main_tests/gmm_probability_test.cpp
  src/mlpack/tests/main_tests/gmm_train_test.cpp
Labels: c: automatic bindings, c: testing, s: needs review, t: added feature

#1761 Highway networks
  src/mlpack/methods/ann/layer/CMakeLists.txt
  src/mlpack/methods/ann/layer/alpha_dropout.hpp
  src/mlpack/methods/ann/layer/highway.hpp
  src/mlpack/methods/ann/layer/highway_impl.hpp
  src/mlpack/methods/ann/layer/layer.hpp
  src/mlpack/methods/ann/layer/layer_types.hpp
  src/mlpack/tests/ann_layer_test.cpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: c: methods, s: needs review, t: added feature

#1948 Copy data for sample Windows installer
  .appveyor.yml
Labels: c: build system, s: needs review, t: bugfix

#1951 Double pole cart environments fix and RL tests
  HISTORY.md
  src/mlpack/methods/reinforcement_learning/environment/CMakeLists.txt
  src/mlpack/methods/reinforcement_learning/environment/continuous_double_pole_cart.hpp
  src/mlpack/methods/reinforcement_learning/environment/continuous_multiple_pole_cart.hpp
  src/mlpack/methods/reinforcement_learning/environment/double_pole_cart.hpp
  src/mlpack/methods/reinforcement_learning/environment/multiple_pole_cart.hpp
  src/mlpack/tests/q_learning_test.cpp
  src/mlpack/tests/rl_components_test.cpp
Labels: c: methods, c: testing, t: bugfix

#1934 [GSoC] Implement probabilistic KDE error bounds
  HISTORY.md
  src/mlpack/core/metrics/lmetric_impl.hpp
  src/mlpack/core/tree/binary_space_tree/dual_tree_traverser_impl.hpp
  src/mlpack/core/tree/binary_space_tree/single_tree_traverser_impl.hpp
  src/mlpack/core/tree/cover_tree/cover_tree_impl.hpp
  src/mlpack/core/tree/octree/dual_tree_traverser_impl.hpp
  src/mlpack/core/tree/octree/single_tree_traverser_impl.hpp
  src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp
  src/mlpack/core/tree/rectangle_tree/rectangle_tree_impl.hpp
  src/mlpack/methods/kde/CMakeLists.txt
  src/mlpack/methods/kde/kde.hpp
  src/mlpack/methods/kde/kde_impl.hpp
  src/mlpack/methods/kde/kde_main.cpp
  src/mlpack/methods/kde/kde_model.hpp
  src/mlpack/methods/kde/kde_model_impl.hpp
  src/mlpack/methods/kde/kde_rules.hpp
  src/mlpack/methods/kde/kde_rules_impl.hpp
  src/mlpack/methods/kde/kde_stat.hpp
  src/mlpack/methods/neighbor_search/neighbor_search_impl.hpp
  src/mlpack/tests/kde_test.cpp
  src/mlpack/tests/knn_test.cpp
  src/mlpack/tests/main_tests/kde_test.cpp
Labels: c: methods, s: needs review, t: added feature

#1959 Remove sudo
  .travis.yml
Labels: c: build system, s: needs review, t: added feature
