Repository mlpack/mlpack, pull requests merged in 2019-09, with the labels that each got.

#2000 double-precision serialization is not lossless
  src/mlpack/methods/cf/normalization/combined_normalization.hpp
  src/mlpack/methods/cf/normalization/item_mean_normalization.hpp
  src/mlpack/methods/cf/normalization/overall_mean_normalization.hpp
  src/mlpack/methods/cf/normalization/user_mean_normalization.hpp
  src/mlpack/methods/cf/normalization/z_score_normalization.hpp
  src/mlpack/tests/cf_test.cpp
Labels: c: methods, c: testing, s: needs review, t: bugfix

#1999 DQN reward-clipping test adjustments.
  src/mlpack/tests/q_learning_test.cpp
  src/mlpack/tests/reward_clipping_test.cpp
Labels: c: testing, s: needs review

#1998 Fix Pendulum task max steps test
  src/mlpack/tests/rl_components_test.cpp
Labels: c: testing, s: needs review, t: bugfix

#1996 Revert Action.action to be a double array
  HISTORY.md
  src/mlpack/methods/reinforcement_learning/environment/continuous_double_pole_cart.hpp
  src/mlpack/methods/reinforcement_learning/environment/continuous_mountain_car.hpp
  src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
  src/mlpack/tests/reward_clipping_test.cpp
  src/mlpack/tests/rl_components_test.cpp
Labels: c: methods, s: needs review

#2002 Increase Linear SVM test tolerance slightly
  src/mlpack/tests/linear_svm_test.cpp
Labels: c: testing, s: needs review, t: bugfix

#2001 Fix very occasional LSH test failures
  src/mlpack/tests/lsh_test.cpp
Labels: c: testing, t: bugfix

#1995 Fix `RandomForestMainTest` random failures
  src/mlpack/tests/main_tests/random_forest_test.cpp
Labels: c: testing, s: needs review, t: bugfix

#2007 Fix `KNNMainTest/KNNAllTreeTypesTest`
  src/mlpack/tests/main_tests/knn_test.cpp
Labels: c: testing, s: needs review, t: bugfix

#2010 Widen tolerance for ssRBMClassificationTest
  src/mlpack/tests/rbm_network_test.cpp
Labels: c: testing, t: bugfix

#2004 Fix intermittent failures in GMMTrainMainTest
  HISTORY.md
  src/mlpack/core/math/random.hpp
  src/mlpack/methods/gmm/gmm_train_main.cpp
  src/mlpack/tests/main_tests/gmm_train_test.cpp
Labels: c: binding, c: testing, s: unanswered, t: bugfix

#2009 Fix occasional `DecisionTreeMainTest` bugs
  src/mlpack/tests/data/braziltourism.arff
  src/mlpack/tests/data/braziltourism_test.arff
  src/mlpack/tests/main_tests/decision_tree_test.cpp
Labels: c: testing, s: needs review, t: bugfix

#2011 ensmallen 2 compatibility fixes
  .travis.yml
  src/mlpack/methods/reinforcement_learning/q_learning.hpp
  src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp
  src/mlpack/methods/reinforcement_learning/worker/n_step_q_learning_worker.hpp
  src/mlpack/methods/reinforcement_learning/worker/one_step_q_learning_worker.hpp
  src/mlpack/methods/reinforcement_learning/worker/one_step_sarsa_worker.hpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: c: methods, c: testing, t: bugfix

#2006 Fix `DecisionTreeTest/PerfectTrainingSet`
  src/mlpack/tests/decision_tree_test.cpp
Labels: c: testing, t: bugfix

#2015 Update Armadillo to minimum version of 8.400.0.
  .appveyor.yml
  .travis.yml
  .travis/config.hpp
  HISTORY.md
  README.md
  doc/guide/build.hpp
  src/mlpack/core/util/arma_config_check.hpp
  src/mlpack/methods/linear_svm/linear_svm_impl.hpp
  src/mlpack/tests/cf_test.cpp
Labels: c: build system, c: documentation, s: needs review, t: bugfix

#2018 Included a useful CMAKE flag
  README.md
  doc/guide/build.hpp
Labels: c: documentation, t: added feature

#2014 Fix occasional `QLearningTest/DoublePoleCartWithDQN` failure.
  src/mlpack/tests/q_learning_test.cpp
Labels: c: methods, c: testing, s: needs review

#2020 LinearSVM test workarounds
  src/mlpack/tests/linear_svm_test.cpp
Labels: c: testing, t: bugfix

#2026 Additional test fixes
  src/mlpack/tests/hmm_test.cpp
  src/mlpack/tests/main_tests/gmm_train_test.cpp
Labels: c: testing, t: bugfix

#2028 Update minimum version of ensmallen.
  CMakeLists.txt
  README.md
  doc/guide/build.hpp
Labels: c: build system, t: bugfix

#2029 Update Armadillo to minimum version of 8.400.0
  CMakeLists.txt
Labels: c: build system, s: needs review, t: bugfix

#2032 Enforce ensmallen version check
  CMake/FindEnsmallen.cmake
  HISTORY.md
Labels: c: build system, t: bugfix

#2022 Fix some potential infinity errors in Naive Bayes Classifier.
  HISTORY.md
  src/mlpack/methods/naive_bayes/naive_bayes_classifier.hpp
  src/mlpack/methods/naive_bayes/naive_bayes_classifier_impl.hpp
  src/mlpack/tests/data/nbc_high_dim_test.csv
  src/mlpack/tests/data/nbc_high_dim_test_labels.csv
  src/mlpack/tests/data/nbc_high_dim_train.csv
  src/mlpack/tests/data/nbc_high_dim_train_labels.csv
  src/mlpack/tests/nbc_test.cpp
Labels: c: methods, t: bugfix

#2034 spelling and grammar in strings
  src/mlpack/core/util/sfinae_utility.hpp
  src/mlpack/methods/kde/kde_main.cpp
  src/mlpack/methods/preprocess/preprocess_scale_main.cpp
Labels: c: documentation, t: bugfix
