Repository mlpack/mlpack, pull requests merged in 2020-12, with the labels that each got.

#2744 Comment change in recurrent
  src/mlpack/methods/ann/layer/recurrent.hpp
  src/mlpack/methods/ann/layer/recurrent_impl.hpp
Labels: c: documentation

#2751 Added FAIL messages to svd_batch_test and argument fix for callback_test.
  src/mlpack/tests/callback_test.cpp
  src/mlpack/tests/svd_batch_test.cpp
Labels: c: testing, s: needs review

#2745 Adding Copy and Move Constructors for RNN and FastLSTM layer.
  src/mlpack/methods/ann/layer/fast_lstm.hpp
  src/mlpack/methods/ann/layer/fast_lstm_impl.hpp
  src/mlpack/methods/ann/rnn.hpp
  src/mlpack/methods/ann/rnn_impl.hpp
  src/mlpack/tests/ann_layer_test.cpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: c: methods, t: added feature

#2748 Adding assert statement to spatial dropout and virtual batch norm
  src/mlpack/methods/ann/layer/spatial_dropout_impl.hpp
  src/mlpack/methods/ann/layer/virtual_batch_norm_impl.hpp
Labels: c: methods, t: added feature

#2740 README instructions for Visual Studio 2019 CMake build
  doc/guide/build_windows.hpp
Labels: c: documentation

#2728 Adding copying and moving constructor for Concatenate Layer
  src/mlpack/methods/ann/layer/concatenate.hpp
  src/mlpack/methods/ann/layer/concatenate_impl.hpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: c: methods, t: added feature

#2688 Avoid accidental deallocations in bindings for Armadillo 10+
  src/mlpack/bindings/go/mlpack/capi/arma_util.hpp
  src/mlpack/bindings/julia/julia_util.cpp
  src/mlpack/bindings/python/mlpack/arma_util.hpp
Labels: c: build system, t: bugfix

#2724 Improved variable names in all loss functions
  src/mlpack/methods/ann/loss_functions/cosine_embedding_loss.hpp
  src/mlpack/methods/ann/loss_functions/cosine_embedding_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/cross_entropy_error.hpp
  src/mlpack/methods/ann/loss_functions/cross_entropy_error_impl.hpp
  src/mlpack/methods/ann/loss_functions/dice_loss.hpp
  src/mlpack/methods/ann/loss_functions/dice_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/earth_mover_distance.hpp
  src/mlpack/methods/ann/loss_functions/earth_mover_distance_impl.hpp
  src/mlpack/methods/ann/loss_functions/empty_loss.hpp
  src/mlpack/methods/ann/loss_functions/empty_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/hinge_embedding_loss.hpp
  src/mlpack/methods/ann/loss_functions/hinge_embedding_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/huber_loss.hpp
  src/mlpack/methods/ann/loss_functions/huber_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/kl_divergence.hpp
  src/mlpack/methods/ann/loss_functions/kl_divergence_impl.hpp
  src/mlpack/methods/ann/loss_functions/l1_loss.hpp
  src/mlpack/methods/ann/loss_functions/l1_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/log_cosh_loss.hpp
  src/mlpack/methods/ann/loss_functions/log_cosh_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/margin_ranking_loss.hpp
  src/mlpack/methods/ann/loss_functions/margin_ranking_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/mean_absolute_percentage_error.hpp
  src/mlpack/methods/ann/loss_functions/mean_absolute_percentage_error_impl.hpp
  src/mlpack/methods/ann/loss_functions/mean_bias_error.hpp
  src/mlpack/methods/ann/loss_functions/mean_bias_error_impl.hpp
  src/mlpack/methods/ann/loss_functions/mean_squared_logarithmic_error.hpp
  src/mlpack/methods/ann/loss_functions/mean_squared_logarithmic_error_impl.hpp
  src/mlpack/methods/ann/loss_functions/negative_log_likelihood.hpp
  src/mlpack/methods/ann/loss_functions/negative_log_likelihood_impl.hpp
  src/mlpack/methods/ann/loss_functions/poisson_nll_loss.hpp
  src/mlpack/methods/ann/loss_functions/poisson_nll_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/reconstruction_loss.hpp
  src/mlpack/methods/ann/loss_functions/reconstruction_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/sigmoid_cross_entropy_error.hpp
  src/mlpack/methods/ann/loss_functions/sigmoid_cross_entropy_error_impl.hpp
  src/mlpack/methods/ann/loss_functions/soft_margin_loss.hpp
  src/mlpack/methods/ann/loss_functions/soft_margin_loss_impl.hpp
Labels: c: methods

#2760 Clarify preprocess_split documentation
  src/mlpack/methods/preprocess/preprocess_split_main.cpp
Labels: c: binding, t: bugfix

#2726 Improve Documentation to correctly state what repositories to get for various Linux distros
  README.md
  doc/guide/build.hpp
Labels: c: documentation

#2767 Fix edge case for similarly-correlated LARS dimensions.
  src/mlpack/methods/lars/lars.cpp
Labels: c: methods, t: bugfix

#2759 Adding Copy and Move constructors for LSTM class
  COPYRIGHT.txt
  src/mlpack/methods/ann/layer/lstm.hpp
  src/mlpack/methods/ann/layer/lstm_impl.hpp
  src/mlpack/tests/ann_layer_test.cpp
Labels: c: methods

#2763 Remove unnecessary _catch suffix from files.
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/adaboost_test.cpp
  src/mlpack/tests/ann_layer_test.cpp
  src/mlpack/tests/ann_regularizer_test.cpp
  src/mlpack/tests/cf_test.cpp
  src/mlpack/tests/convolution_test.cpp
  src/mlpack/tests/convolutional_network_test.cpp
  src/mlpack/tests/dcgan_test.cpp
  src/mlpack/tests/decision_tree_test.cpp
  src/mlpack/tests/distribution_test.cpp
  src/mlpack/tests/drusilla_select_test.cpp
  src/mlpack/tests/fastmks_test.cpp
  src/mlpack/tests/feedforward_network_2_test.cpp
  src/mlpack/tests/feedforward_network_test.cpp
  src/mlpack/tests/gan_test.cpp
  src/mlpack/tests/hoeffding_tree_test.cpp
  src/mlpack/tests/image_load_test.cpp
  src/mlpack/tests/kde_test.cpp
  src/mlpack/tests/kernel_test.cpp
  src/mlpack/tests/linear_regression_test.cpp
  src/mlpack/tests/local_coordinate_coding_test.cpp
  src/mlpack/tests/octree_test.cpp
  src/mlpack/tests/qdafn_test.cpp
  src/mlpack/tests/random_forest_test.cpp
  src/mlpack/tests/recurrent_network_test.cpp
  src/mlpack/tests/rnn_reber_test.cpp
  src/mlpack/tests/serialization.cpp
  src/mlpack/tests/serialization.hpp
  src/mlpack/tests/serialization_test.cpp
  src/mlpack/tests/sparse_coding_test.cpp
  src/mlpack/tests/string_encoding_test.cpp
  src/mlpack/tests/wgan_test.cpp
Labels: c: testing

#2766 Update COPYRIGHT (year).
  COPYRIGHT.txt
Labels: c: documentation

#2756 Fix garbage collection for Julia mlpack models
  CMake/julia/AppendType.cmake
  CMake/julia/ConfigureJuliaHCPP.cmake
  HISTORY.md
  src/mlpack/bindings/julia/print_input_processing_impl.hpp
  src/mlpack/bindings/julia/print_jl.cpp
  src/mlpack/bindings/julia/print_output_processing_impl.hpp
  src/mlpack/bindings/julia/print_param_defn.hpp
  src/mlpack/bindings/julia/tests/runtests.jl
  src/mlpack/bindings/julia/tests/test_julia_binding_main.cpp
Labels: c: automatic bindings, t: bugfix

#2771 Update build.hpp
  COPYRIGHT.txt
  doc/guide/build.hpp
  src/mlpack/tests/README.md
Labels: c: documentation

#2706 Adding WeightSize() to transposed convolution, celu, c_relu, noisy_linear and parametric relu
  src/mlpack/methods/ann/layer/c_relu.hpp
  src/mlpack/methods/ann/layer/celu.hpp
  src/mlpack/methods/ann/layer/leaky_relu.hpp
  src/mlpack/methods/ann/layer/noisylinear.hpp
  src/mlpack/methods/ann/layer/noisylinear_impl.hpp
  src/mlpack/methods/ann/layer/parametric_relu.hpp
  src/mlpack/methods/ann/layer/parametric_relu_impl.hpp
  src/mlpack/methods/ann/layer/transposed_convolution.hpp
  src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp
  src/mlpack/tests/ann_visitor_test.cpp
Labels: c: methods, t: added feature

#2266 Removing decision stump class
  src/mlpack/methods/CMakeLists.txt
  src/mlpack/methods/adaboost/adaboost.hpp
  src/mlpack/methods/decision_stump/CMakeLists.txt
  src/mlpack/methods/decision_stump/decision_stump.hpp
  src/mlpack/methods/decision_stump/decision_stump_impl.hpp
  src/mlpack/methods/decision_stump/decision_stump_main.cpp
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/decision_stump_test.cpp
  src/mlpack/tests/decision_tree_test.cpp
  src/mlpack/tests/serialization_test.cpp
Labels: c: methods, s: keep open

#2739 Adding clear errors to RNN's and FFN's when the input shape is wrong
  src/mlpack/methods/ann/CMakeLists.txt
  src/mlpack/methods/ann/ffn_impl.hpp
  src/mlpack/methods/ann/layer/atrous_convolution.hpp
  src/mlpack/methods/ann/layer/bilinear_interpolation.hpp
  src/mlpack/methods/ann/layer/convolution.hpp
  src/mlpack/methods/ann/layer/fast_lstm.hpp
  src/mlpack/methods/ann/layer/glimpse.hpp
  src/mlpack/methods/ann/layer/gru.hpp
  src/mlpack/methods/ann/layer/highway.hpp
  src/mlpack/methods/ann/layer/layer_norm.hpp
  src/mlpack/methods/ann/layer/layer_traits.hpp
  src/mlpack/methods/ann/layer/linear.hpp
  src/mlpack/methods/ann/layer/linear3d.hpp
  src/mlpack/methods/ann/layer/linear_no_bias.hpp
  src/mlpack/methods/ann/layer/lstm.hpp
  src/mlpack/methods/ann/layer/minibatch_discrimination.hpp
  src/mlpack/methods/ann/layer/multihead_attention.hpp
  src/mlpack/methods/ann/layer/noisylinear.hpp
  src/mlpack/methods/ann/layer/positional_encoding.hpp
  src/mlpack/methods/ann/layer/radial_basis_function.hpp
  src/mlpack/methods/ann/layer/recurrent.hpp
  src/mlpack/methods/ann/layer/recurrent_impl.hpp
  src/mlpack/methods/ann/layer/reparametrization.hpp
  src/mlpack/methods/ann/layer/sequential.hpp
  src/mlpack/methods/ann/layer/sequential_impl.hpp
  src/mlpack/methods/ann/layer/transposed_convolution.hpp
  src/mlpack/methods/ann/rnn_impl.hpp
  src/mlpack/methods/ann/util/CMakeLists.txt
  src/mlpack/methods/ann/util/check_input_shape.hpp
  src/mlpack/methods/ann/visitor/CMakeLists.txt
  src/mlpack/methods/ann/visitor/input_shape_visitor.hpp
  src/mlpack/methods/ann/visitor/input_shape_visitor_impl.hpp
  src/mlpack/tests/feedforward_network_test.cpp
  src/mlpack/tests/recurrent_network_test.cpp
Labels: c: methods, t: added feature

#2778 Gonum can't hold ints, so remove slightly confusing documentation.
  src/mlpack/bindings/go/get_printable_type_impl.hpp
  src/mlpack/bindings/go/print_type_doc_impl.hpp
Labels: c: automatic bindings

#2762 Adding triplet margin loss function
  HISTORY.md
  src/mlpack/methods/ann/loss_functions/CMakeLists.txt
  src/mlpack/methods/ann/loss_functions/triplet_margin_loss.hpp
  src/mlpack/methods/ann/loss_functions/triplet_margin_loss_impl.hpp
  src/mlpack/tests/loss_functions_test.cpp
Labels: c: methods, t: added feature

#2780 Scheduled cron GH-action workflow for updating Boost version.
  .github/workflows/update-boost-version.yaml
  CMakeLists.txt
Labels: c: build system

#2782 Disabling bindings by default in cmake.
  CMakeLists.txt
  HISTORY.md
Labels: c: automatic bindings

#2785 Fix indentation
  CMake/Findcereal.cmake
Labels: c: build system

#2624 Added Adjusted R2
  HISTORY.md
  src/mlpack/core/cv/metrics/r2_score.hpp
  src/mlpack/core/cv/metrics/r2_score_impl.hpp
  src/mlpack/tests/cv_test.cpp
Labels: c: methods, t: added feature
