Repository mlpack/mlpack, pull requests merged in 2020-09, with the labels that each got.

#2595 Handle NaNs and infs in KFoldCV scores
  HISTORY.md
  src/mlpack/core/cv/k_fold_cv_impl.hpp
  src/mlpack/tests/cv_test.cpp
Labels: c: core, t: bugfix

#2593 Migrate _network_* test from boost to catch
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/feedforward_network_test.cpp
  src/mlpack/tests/rbm_network_test.cpp
  src/mlpack/tests/recurrent_network_test.cpp
Labels: c: testing

#2600 Prepend "--" to options when checking that they are there.
  HISTORY.md
  src/mlpack/bindings/cli/parse_command_line.hpp
  src/mlpack/tests/io_test.cpp
Labels: c: automatic bindings, t: bugfix

#2605 Update configuration variables and updating as it was earlier done in issue #2604
  CMakeLists.txt
Labels: c: build system

#2602 Add manual specification of file type to data::Load().
  HISTORY.md
  src/mlpack/core/data/CMakeLists.txt
  src/mlpack/core/data/detect_file_type.cpp
  src/mlpack/core/data/detect_file_type.hpp
  src/mlpack/core/data/load.cpp
  src/mlpack/core/data/load.hpp
  src/mlpack/core/data/load_impl.hpp
  src/mlpack/core/data/save.hpp
  src/mlpack/core/data/save_impl.hpp
  src/mlpack/tests/load_save_test.cpp
Labels: c: core, t: added feature, t: bugfix

#2609 grammar
  src/mlpack/bindings/cli/third_party/CLI/CLI11.hpp
  src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression_main.cpp
Labels: c: documentation, t: bugfix

#2618 Fix regex for versions of Go without a patch version
  CMake/FindGo.cmake
Labels: c: automatic bindings, c: build system, t: bugfix

#2608 Added post_x_bindings methods for Python, Go and Julia bindings
  src/mlpack/CMakeLists.txt
  src/mlpack/bindings/go/CMakeLists.txt
  src/mlpack/bindings/julia/CMakeLists.txt
  src/mlpack/bindings/python/CMakeLists.txt
Labels: c: binding, t: added feature

#2617 Clarify that the type should be size_t for numClasses in CVBase
  src/mlpack/core/cv/cv_base_impl.hpp
Labels: c: core, t: added feature

#2583 Adding copy constructor in linear layer
  src/mlpack/methods/ann/ffn_impl.hpp
  src/mlpack/methods/ann/layer/linear.hpp
  src/mlpack/methods/ann/layer/linear_impl.hpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: t: added feature

#2622 Addition of Mean Absolute Percentage Error
  HISTORY.md
  src/mlpack/methods/ann/loss_functions/CMakeLists.txt
  src/mlpack/methods/ann/loss_functions/mean_absolute_percentage_error.hpp
  src/mlpack/methods/ann/loss_functions/mean_absolute_percentage_error_impl.hpp
  src/mlpack/tests/loss_functions_test.cpp
Labels: c: methods, t: added feature

#2627 migrate arma_extend_test from boost to catch2
  COPYRIGHT.txt
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/arma_extend_test.cpp
Labels: c: testing

#2629 Migrate DBSCAN test from boost to catch2
  COPYRIGHT.txt
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/dbscan_test.cpp
  src/mlpack/tests/main_tests/dbscan_test.cpp
Labels: c: testing

#2631 Migrating Random Forest tests from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/main_tests/random_forest_test.cpp
  src/mlpack/tests/random_forest_test.cpp
Labels: c: testing

#2586 Migrate PCA related tests from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/main_tests/pca_test.cpp
  src/mlpack/tests/pca_test.cpp
Labels: c: testing
