Repository mlpack/mlpack, pull requests merged in 2020-11, with the labels that each got.

#2689 Scheduled cron GH-action workflow for updating headers.
  .github/workflows/update-catch.yaml
  .github/workflows/update-cli11.yaml
Labels: c: build system

#2701 Added WeighSize() to Softmax, Max_Pooling and Min_Pooling layers.
  src/mlpack/methods/ann/layer/max_pooling.hpp
  src/mlpack/methods/ann/layer/mean_pooling.hpp
  src/mlpack/methods/ann/layer/softmax.hpp
Labels: c: methods, t: added feature

#2678 Migrate multiple tests from Boost to Catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/drusilla_select_test.cpp
  src/mlpack/tests/emst_test.cpp
  src/mlpack/tests/facilities_test.cpp
  src/mlpack/tests/fastmks_test.cpp
  src/mlpack/tests/hpt_test.cpp
  src/mlpack/tests/hyperplane_test.cpp
  src/mlpack/tests/init_rules_test.cpp
  src/mlpack/tests/lars_test.cpp
  src/mlpack/tests/linear_svm_test.cpp
  src/mlpack/tests/local_coordinate_coding_test.cpp
  src/mlpack/tests/log_test.cpp
  src/mlpack/tests/logistic_regression_test.cpp
  src/mlpack/tests/lsh_test.cpp
  src/mlpack/tests/main_tests/emst_test.cpp
  src/mlpack/tests/main_tests/fastmks_test.cpp
  src/mlpack/tests/main_tests/linear_svm_test.cpp
  src/mlpack/tests/main_tests/local_coordinate_coding_test.cpp
  src/mlpack/tests/main_tests/logistic_regression_test.cpp
  src/mlpack/tests/main_tests/lsh_test.cpp
  src/mlpack/tests/main_tests/perceptron_test.cpp
  src/mlpack/tests/matrix_completion_test.cpp
  src/mlpack/tests/maximal_inputs_test.cpp
  src/mlpack/tests/q_learning_test.cpp
  src/mlpack/tests/qdafn_test.cpp
  src/mlpack/tests/random_test.cpp
  src/mlpack/tests/termination_policy_test.cpp
  src/mlpack/tests/timer_test.cpp
  src/mlpack/tests/union_find_test.cpp
Labels: c: testing

#2684 Migrate serialization test from boost to catch
  .appveyor.yml
  .ci/windows-steps.yaml
  CMakeLists.txt
  README.md
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/README.md
  src/mlpack/tests/callback_test.cpp
  src/mlpack/tests/decision_tree_test.cpp
  src/mlpack/tests/main_tests/det_test.cpp
  src/mlpack/tests/main_tests/softmax_regression_test.cpp
  src/mlpack/tests/mlpack_test.cpp
  src/mlpack/tests/range_search_test.cpp
  src/mlpack/tests/serialization.cpp
  src/mlpack/tests/serialization.hpp
  src/mlpack/tests/serialization_test.cpp
  src/mlpack/tests/string_encoding_test.cpp
  src/mlpack/tests/test_tools.hpp
Labels: c: testing, s: unanswered

#2671 Added an implementation to Stratify Data
  HISTORY.md
  src/mlpack/core/data/split_data.hpp
  src/mlpack/methods/preprocess/preprocess_split_main.cpp
  src/mlpack/tests/main_tests/preprocess_split_test.cpp
  src/mlpack/tests/split_data_test.cpp
Labels: c: methods, t: added feature

#2685 Fix Windows-R warnings.
  .github/workflows/main.yml
  README.md
  src/mlpack/bindings/R/CMakeLists.txt
  src/mlpack/bindings/R/mlpack/DESCRIPTION.in
  src/mlpack/methods/preprocess/preprocess_split_main.cpp
Labels: c: automatic bindings, c: build system

#2716 adding FAIL message to akfn_test, aknn_test and 4 more tests when calling data::Load
  COPYRIGHT.txt
  src/mlpack/tests/akfn_test.cpp
  src/mlpack/tests/aknn_test.cpp
  src/mlpack/tests/callback_test.cpp
  src/mlpack/tests/cf_test.cpp
  src/mlpack/tests/decision_tree_test.cpp
  src/mlpack/tests/facilities_test.cpp
Labels: c: testing, t: added feature

#2719 Scheduled workflow must run on main repository only.
  .github/workflows/main.yml
  .github/workflows/update-catch.yaml
  .github/workflows/update-cli11.yaml
Labels: c: build system, t: bugfix

#2704 Adding Copy and Move constructors in Dropout Layer
  src/mlpack/methods/ann/layer/dropout.hpp
  src/mlpack/methods/ann/layer/dropout_impl.hpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: c: methods

#2730 Add BUILD_DOCS option to enable/disable building documentation.
  CMakeLists.txt
  Doxyfile
  HISTORY.md
  README.md
  doc/guide/build.hpp
Labels: c: build system, t: added feature

#2708 Changed all the deprecated armadillo matrix initializations with the new braced initializer list
  src/mlpack/core/math/columns_to_blocks.hpp
  src/mlpack/tests/binarize_test.cpp
  src/mlpack/tests/convolution_test.cpp
  src/mlpack/tests/cv_test.cpp
  src/mlpack/tests/decision_stump_test.cpp
  src/mlpack/tests/det_test.cpp
  src/mlpack/tests/distribution_test.cpp
  src/mlpack/tests/facilities_test.cpp
  src/mlpack/tests/linear_regression_test.cpp
  src/mlpack/tests/logistic_regression_test.cpp
  src/mlpack/tests/lsh_test.cpp
  src/mlpack/tests/main_tests/logistic_regression_test.cpp
  src/mlpack/tests/main_tests/perceptron_test.cpp
  src/mlpack/tests/maximal_inputs_test.cpp
  src/mlpack/tests/perceptron_test.cpp
  src/mlpack/tests/rnn_reber_test.cpp
Labels: c: testing

#2734 changed comments in convolution.hpp
  src/mlpack/methods/ann/layer/convolution.hpp
Labels: c: documentation

#2712 some boost cleanup
  .appveyor.yml
  CMakeLists.txt
  doc/guide/build.hpp
  doc/guide/build_windows.hpp
  doc/guide/sample_ml_app.hpp
  src/mlpack/bindings/cli/CMakeLists.txt
  src/mlpack/bindings/python/CMakeLists.txt
  src/mlpack/bindings/python/setup.py.in
  src/mlpack/tests/CMakeLists.txt
Labels: c: testing

#2729 Add copying and moving constructor for NoisyLinear layer
  src/mlpack/methods/ann/layer/noisylinear.hpp
  src/mlpack/methods/ann/layer/noisylinear_impl.hpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: c: methods

#2714 Improved variable names in MSE
  src/mlpack/methods/ann/loss_functions/mean_squared_error.hpp
  src/mlpack/methods/ann/loss_functions/mean_squared_error_impl.hpp
Labels: c: methods

#2711 Added copy and move constructors to Linear3D Layer
  COPYRIGHT.txt
  src/mlpack/methods/ann/layer/linear3d.hpp
  src/mlpack/methods/ann/layer/linear3d_impl.hpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: c: methods

#2664 Use Azure to build the MSI installer
  .ci/ci.yaml
  .ci/windows-steps.yaml
  dist/win-installer/mlpack-win-installer/Product.wxs
  dist/win-installer/mlpack-win-installer/mlpack-win-installer.wixproj
Labels: c: build system
