Repository mlpack/mlpack, pull requests merged in 2020-07, with the labels that each got.

#2488 Fix equation definition.
  src/mlpack/methods/ann/rbm/rbm.hpp
Labels: c: documentation, t: bugfix

#2486 Some fixes for the ARFF loader
  HISTORY.md
  src/mlpack/core/data/load_arff_impl.hpp
  src/mlpack/methods/decision_tree/decision_tree_main.cpp
  src/mlpack/tests/data/braziltourism.arff
  src/mlpack/tests/data/braziltourism_test.arff
  src/mlpack/tests/main_tests/decision_tree_test.cpp
Labels: c: methods, s: unanswered, t: added feature, t: bugfix

#2491 Some Style Fixes.
  src/mlpack/core/tree/cellbound_impl.hpp
Labels: c: documentation

#2499 Linking RL tutorial
  doc/tutorials/tutorials.txt
Labels: c: documentation

#2196 [MRG] adding poisson nll loss function
  HISTORY.md
  src/mlpack/methods/ann/loss_functions/CMakeLists.txt
  src/mlpack/methods/ann/loss_functions/poisson_nll_loss.hpp
  src/mlpack/methods/ann/loss_functions/poisson_nll_loss_impl.hpp
  src/mlpack/tests/loss_functions_test.cpp
Labels: c: methods, t: added feature

#2502 Update to soversion libmlpack.so.3.3
  src/mlpack/CMakeLists.txt
Labels: c: build system, t: bugfix

#2503 Test stability fixes
  src/mlpack/tests/linear_svm_test.cpp
  src/mlpack/tests/logistic_regression_test.cpp
  src/mlpack/tests/main_tests/nca_test.cpp
  src/mlpack/tests/nmf_test.cpp
Labels: c: testing, t: bugfix

#2481 Add feature request Issue Template
  .github/ISSUE_TEMPLATE/3-feature_request.md
Labels: c: documentation, t: added feature

#2442 Krann Test
  src/mlpack/methods/rann/krann_main.cpp
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/main_tests/krann_test.cpp
Labels: c: testing

#2497 Adding support to use gym_tcp_api for training agents in q_learning
  src/mlpack/methods/reinforcement_learning/environment/CMakeLists.txt
  src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp
  src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp
  src/mlpack/methods/reinforcement_learning/environment/double_pole_cart.hpp
  src/mlpack/methods/reinforcement_learning/environment/env_type.hpp
  src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
  src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
  src/mlpack/methods/reinforcement_learning/policy/greedy_policy.hpp
  src/mlpack/methods/reinforcement_learning/q_learning.hpp
  src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp
  src/mlpack/methods/reinforcement_learning/replay/prioritized_replay.hpp
  src/mlpack/methods/reinforcement_learning/replay/random_replay.hpp
  src/mlpack/methods/reinforcement_learning/training_config.hpp
  src/mlpack/methods/reinforcement_learning/worker/n_step_q_learning_worker.hpp
  src/mlpack/methods/reinforcement_learning/worker/one_step_q_learning_worker.hpp
  src/mlpack/methods/reinforcement_learning/worker/one_step_sarsa_worker.hpp
  src/mlpack/tests/q_learning_test.cpp
  src/mlpack/tests/rl_components_test.cpp
Labels: c: methods, t: added feature

#2507 Fix version of Julia in documentation.
  README.md
Labels: c: documentation, t: bugfix

#2510 remove and ignore vim temp files
  .gitignore
  src/mlpack/methods/decision_tree/.all_categorical_split_impl.hpp.swp
  src/mlpack/methods/decision_tree/.best_binary_numeric_split_impl.hpp.swp
  src/mlpack/methods/decision_tree/.decision_tree_impl.hpp.swp
Labels: c: documentation, t: bugfix

#2474 Extending Support of BatchNorm layer to Convolutional Layer output.
  src/mlpack/methods/ann/layer/batch_norm.hpp
  src/mlpack/methods/ann/layer/batch_norm_impl.hpp
  src/mlpack/tests/ann_layer_test.cpp
Labels: c: methods, t: bugfix

#2513 No reason to run the test suite twice.
  .ci/windows-steps.yaml
Labels: c: testing

#2516 Fix ARFF loader to be case sensitive
  HISTORY.md
  src/mlpack/core/data/load_arff_impl.hpp
  src/mlpack/tests/load_save_test.cpp
Labels: c: core, t: bugfix

#2517 move cxx11 target_compile_features call
  CMake/NewCXX11.cmake
  src/mlpack/CMakeLists.txt
Labels: c: build system

#2518 fix reorder warnings in batch norm
  src/mlpack/methods/ann/layer/batch_norm.hpp
Labels: c: methods

#2515 Doc changes for q_learning
  doc/tutorials/reinforcement_learning/reinforcement_learning.txt
Labels: c: documentation, s: unanswered

#2457 Re write test using catch
  Doxyfile
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/catch.hpp
  src/mlpack/tests/image_load_test.cpp
  src/mlpack/tests/main.cpp
  src/mlpack/tests/main_tests/image_converter_test.cpp
  src/mlpack/tests/serialization_catch.cpp
  src/mlpack/tests/serialization_catch.hpp
  src/mlpack/tests/test_catch_tools.hpp
Labels: c: testing, t: added feature

#2522 fixed a typo that the caused incorrect configuration of the cmake
  CMake/mlpack-config.cmake.in
Labels: c: build system, s: unanswered, t: bugfix

#2520 Fix Bad Regex from CLI11.
  doc/guide/cli_quickstart.hpp
  doc/guide/iodoc.hpp
  doc/guide/timer.hpp
  src/mlpack/bindings/go/default_param.hpp
  src/mlpack/bindings/go/go_option.hpp
  src/mlpack/bindings/go/mlpack/capi/arma_util.cpp
  src/mlpack/bindings/go/print_doc_functions.hpp
  src/mlpack/bindings/go/print_doc_functions_impl.hpp
  src/mlpack/bindings/go/print_input_processing.hpp
  src/mlpack/bindings/markdown/print_doc_functions.hpp
  src/mlpack/bindings/markdown/print_docs.hpp
  src/mlpack/bindings/tests/clean_memory.cpp
  src/mlpack/bindings/tests/clean_memory.hpp
  src/mlpack/bindings/tests/delete_allocated_memory.hpp
  src/mlpack/bindings/tests/get_allocated_memory.hpp
  src/mlpack/bindings/tests/test_option.hpp
  src/mlpack/core/util/mlpack_main.hpp
  src/mlpack/core/util/param.hpp
  src/mlpack/core/util/param_checks.hpp
  src/mlpack/tests/prefixedoutstream_test.cpp
  src/mlpack/tests/python_binding_test.cpp
Labels: c: documentation, s: unanswered

#2530 Fix ModelType Julia Documentation.
  src/mlpack/bindings/julia/print_doc.hpp
Labels: c: automatic bindings, c: binding, c: documentation, s: needs review, t: bugfix

#2525 Transition activation_functions_test.cpp to Catch
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/activation_functions_test.cpp
Labels: c: testing

#2526 Migrate linear regression tests from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/image_load_test.cpp
  src/mlpack/tests/linear_regression_test.cpp
  src/mlpack/tests/main_tests/image_converter_test.cpp
  src/mlpack/tests/main_tests/linear_regression_test.cpp
Labels: c: testing, s: needs review

#2528 Migrate adaboost test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/adaboost_test.cpp
  src/mlpack/tests/main_tests/adaboost_test.cpp
Labels: c: testing

#2527 Migrate softmax regression test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/main_tests/softmax_regression_test.cpp
  src/mlpack/tests/softmax_regression_test.cpp
Labels: c: testing, t: added feature

#2533 Migrate Convolution Tests from Boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/convolution_test.cpp
  src/mlpack/tests/convolutional_network_test.cpp
Labels: c: testing, t: added feature

#2484 GCC 10 and Clang 10 build warnings fixes
  src/mlpack/bindings/julia/julia_util.cpp
  src/mlpack/core/metrics/iou_metric_impl.hpp
  src/mlpack/core/metrics/non_maximal_supression_impl.hpp
  src/mlpack/methods/amf/termination_policies/simple_tolerance_termination.hpp
  src/mlpack/methods/ann/brnn_impl.hpp
  src/mlpack/methods/ann/gan/metrics/inception_score_impl.hpp
  src/mlpack/methods/ann/layer/gru_impl.hpp
  src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp
  src/mlpack/methods/ann/layer/vr_class_reward.hpp
  src/mlpack/methods/ann/layer/vr_class_reward_impl.hpp
  src/mlpack/methods/ann/loss_functions/cosine_embedding_loss.hpp
  src/mlpack/methods/ann/loss_functions/cosine_embedding_loss_impl.hpp
  src/mlpack/methods/ann/loss_functions/negative_log_likelihood_impl.hpp
  src/mlpack/methods/ann/rnn_impl.hpp
  src/mlpack/methods/gmm/gmm_train_main.cpp
  src/mlpack/methods/lmnn/lmnn_main.cpp
  src/mlpack/methods/rann/krann_main.cpp
  src/mlpack/methods/reinforcement_learning/q_networks/dueling_dqn.hpp
  src/mlpack/tests/image_load_test.cpp
  src/mlpack/tests/main_tests/decision_tree_test.cpp
  src/mlpack/tests/main_tests/hoeffding_tree_test.cpp
  src/mlpack/tests/recurrent_network_test.cpp
Labels: c: build system, t: bugfix

#2541 Fix data in sample ML app to be column-major.
  doc/guide/sample_ml_app.hpp
Labels: c: documentation, t: bugfix

#2535 Migrate KFN, KNN and related test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/akfn_test.cpp
  src/mlpack/tests/aknn_test.cpp
  src/mlpack/tests/kfn_test.cpp
  src/mlpack/tests/knn_test.cpp
  src/mlpack/tests/main_tests/approx_kfn_test.cpp
  src/mlpack/tests/main_tests/kfn_test.cpp
  src/mlpack/tests/main_tests/knn_test.cpp
Labels: c: testing, t: added feature

#2536 migrate load and save test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/load_save_test.cpp
Labels: c: testing

#2540 Changes to the network initialization methods in Q_learning networks
  src/mlpack/methods/reinforcement_learning/q_networks/dueling_dqn.hpp
  src/mlpack/methods/reinforcement_learning/q_networks/simple_dqn.hpp
Labels: c: methods, t: bugfix

#2542 [Ready] App Veyor build fix
  src/mlpack/tests/metric_test.cpp
Labels: c: build system, t: bugfix

#2546 Migrate svd_* and related test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/armadillo_svd_test.cpp
  src/mlpack/tests/bias_svd_test.cpp
  src/mlpack/tests/block_krylov_svd_test.cpp
  src/mlpack/tests/quic_svd_test.cpp
  src/mlpack/tests/randomized_svd_test.cpp
  src/mlpack/tests/regularized_svd_test.cpp
  src/mlpack/tests/svd_batch_test.cpp
  src/mlpack/tests/svd_incremental_test.cpp
  src/mlpack/tests/svdplusplus_test.cpp
Labels: c: testing

#2548 Add tests for Convolutional layer.
  src/mlpack/tests/ann_layer_test.cpp
Labels: c: testing, t: added feature
