Repository mlpack/mlpack, pull requests merged in 2020-10, with the labels that each got.

#2638 Loss_function_test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/loss_functions_test.cpp
Labels: c: testing

#2626 Add WeightSize() to Linear, Add and Atrous Convolution layers.
  src/mlpack/methods/ann/layer/add.hpp
  src/mlpack/methods/ann/layer/atrous_convolution.hpp
  src/mlpack/methods/ann/layer/linear.hpp
  src/mlpack/tests/ann_visitor_test.cpp
Labels: c: methods, t: added feature

#2642 Enable auto cancel build on new push and cache for build.
  .ci/windows-steps.yaml
  .github/workflows/main.yml
  src/mlpack/tests/random_forest_test.cpp
Labels: c: build system

#2621 Addition of softmin activation function
  HISTORY.md
  src/mlpack/methods/ann/layer/CMakeLists.txt
  src/mlpack/methods/ann/layer/layer.hpp
  src/mlpack/methods/ann/layer/softmin.hpp
  src/mlpack/methods/ann/layer/softmin_impl.hpp
  src/mlpack/tests/activation_functions_test.cpp
Labels: c: methods, t: added feature

#2639 Increase Threshold for some tests where common failure occurs.
  src/mlpack/tests/ann_layer_test.cpp
  src/mlpack/tests/feedforward_network_test.cpp
Labels: c: testing

#2653 Migrate det and distribution test to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/det_test.cpp
  src/mlpack/tests/distribution_test.cpp
Labels: c: testing, s: needs review

#2584 Catch test part 2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/cli_binding_test.cpp
  src/mlpack/tests/io_test.cpp
Labels: c: testing

#2655 Migrate sort_policy, sfinae and string related test to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/sfinae_test.cpp
  src/mlpack/tests/sort_policy_test.cpp
  src/mlpack/tests/string_encoding_test.cpp
Labels: c: testing

#2657 Forward implementation changed for softmin and softmax activation function
  src/mlpack/methods/ann/layer/softmax_impl.hpp
  src/mlpack/methods/ann/layer/softmin_impl.hpp
Labels: c: methods

#2645 Migrate metric test from Boost to Catch2Migration
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/metric_test.cpp
Labels: c: testing

#2665 Pass CMAKE_SIZEOF_VOID_P explicitly to CreateArmaConfig.cmake
  CMakeLists.txt
  HISTORY.md
Labels: c: build system, t: bugfix

#2654 Migrate layers_names, line_alg and lars test to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/lars_test.cpp
  src/mlpack/tests/layer_names_test.cpp
  src/mlpack/tests/lin_alg_test.cpp
Labels: c: testing

#2659 Remove R-bindings build from azure pipeline.
  .ci/ci.yaml
  .ci/linux-steps.yaml
  .ci/macos-steps.yaml
  .github/workflows/main.yml
Labels: c: build system, s: needs review

#2644 Migrate range_search_test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/main_tests/range_search_test.cpp
  src/mlpack/tests/main_tests/range_search_utils.hpp
  src/mlpack/tests/range_search_test.cpp
Labels: c: testing

#2577 migrate _tree_test_* related test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/cosine_tree_test.cpp
  src/mlpack/tests/hoeffding_tree_test.cpp
  src/mlpack/tests/main_tests/hoeffding_tree_test.cpp
  src/mlpack/tests/octree_test.cpp
  src/mlpack/tests/rectangle_tree_test.cpp
  src/mlpack/tests/spill_tree_test.cpp
  src/mlpack/tests/sumtree_test.cpp
  src/mlpack/tests/tree_test.cpp
  src/mlpack/tests/tree_traits_test.cpp
  src/mlpack/tests/ub_tree_test.cpp
  src/mlpack/tests/vantage_point_tree_test.cpp
Labels: c: testing

#2661 Fix R-bindings documentation.
  src/mlpack/bindings/R/print_R.cpp
  src/mlpack/bindings/R/print_doc_functions_impl.hpp
  src/mlpack/bindings/markdown/print_docs.cpp
Labels: c: automatic bindings, c: documentation, t: bugfix

#2652 Migrate Augmentated_rnn and Async_Learning Test to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/async_learning_test.cpp
  src/mlpack/tests/augmented_rnns_tasks_test.cpp
Labels: c: testing

#2539 Migrate gmm and hmm related test from boost to catch
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/gmm_test.cpp
  src/mlpack/tests/hmm_test.cpp
  src/mlpack/tests/main_tests/gmm_generate_test.cpp
  src/mlpack/tests/main_tests/gmm_probability_test.cpp
  src/mlpack/tests/main_tests/gmm_train_test.cpp
  src/mlpack/tests/main_tests/hmm_generate_test.cpp
  src/mlpack/tests/main_tests/hmm_loglik_test.cpp
  src/mlpack/tests/main_tests/hmm_train_test.cpp
  src/mlpack/tests/main_tests/hmm_viterbi_test.cpp
Labels: c: testing

#2669 Migration of GAN related tests and math test to Catch2 Testing
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/dcgan_test.cpp
  src/mlpack/tests/gan_test.cpp
  src/mlpack/tests/math_test.cpp
  src/mlpack/tests/wgan_test.cpp
Labels: c: testing

#2673 Migrate krann and cf-Test from boost to catch2
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/cf_test.cpp
  src/mlpack/tests/krann_search_test.cpp
  src/mlpack/tests/ksinit_test.cpp
  src/mlpack/tests/main_tests/cf_test.cpp
  src/mlpack/tests/main_tests/krann_test.cpp
Labels: c: testing

#2660 Fix macOS Python build on Azure
  .ci/ci.yaml
  .ci/macos-steps.yaml
Labels: t: bugfix

#2637 Add WeightSize to BatchNorm and Conv Layer.
  src/mlpack/methods/ann/layer/batch_norm.hpp
  src/mlpack/methods/ann/layer/batch_norm_impl.hpp
  src/mlpack/methods/ann/layer/convolution.hpp
  src/mlpack/methods/ann/layer/convolution_impl.hpp
  src/mlpack/tests/ann_visitor_test.cpp
Labels: c: methods

#2675 Migrate kde, lmnn , rl and rewardclipping test to catch
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/kde_test.cpp
  src/mlpack/tests/lmnn_test.cpp
  src/mlpack/tests/main_tests/kde_test.cpp
  src/mlpack/tests/main_tests/lmnn_test.cpp
  src/mlpack/tests/reward_clipping_test.cpp
  src/mlpack/tests/rl_components_test.cpp
Labels: c: testing

#2680 Fix github-actions build for R-bindings.
  CMake/FindRModule.cmake
Labels: c: build system

#2683 Add release scripts
  scripts/release-mlpack.sh
  scripts/update-website-after-release.sh
Labels: t: added feature

#2650 Added Weight Size to concat and fast_lstm layers and
  src/mlpack/methods/ann/layer/add_impl.hpp
  src/mlpack/methods/ann/layer/atrous_convolution_impl.hpp
  src/mlpack/methods/ann/layer/concat.hpp
  src/mlpack/methods/ann/layer/concat_impl.hpp
  src/mlpack/methods/ann/layer/dropconnect.hpp
  src/mlpack/methods/ann/layer/fast_lstm.hpp
  src/mlpack/methods/ann/layer/fast_lstm_impl.hpp
  src/mlpack/methods/ann/layer/linear_impl.hpp
  src/mlpack/tests/ann_visitor_test.cpp
Labels: c: methods, t: added feature
