Repository mlpack/mlpack, pull requests merged in 2020-01, with the labels that each got.

#2133 removed using namespace std from pca_imp.hpp
  src/mlpack/methods/pca/pca_impl.hpp
Labels: c: methods, s: needs review

#2143 Updated documentation to include mlpack image utilities
  doc/guide/formats.hpp
  doc/tutorials/image/image.txt
Labels: c: documentation, s: needs review, t: added feature

#2145 Safer adding of stb/ suffix to include directory.
  CMake/FindStbImage.cmake
  HISTORY.md
Labels: c: build system, t: bugfix

#2144 Update readme.md and build.hpp
  README.md
  doc/guide/build.hpp
Labels: c: documentation, s: needs review, t: added feature

#2148 Fix handling of directories with spaces for CMake Python binding configuration
  src/mlpack/CMakeLists.txt
  src/mlpack/bindings/python/ConfigureSetup.cmake
  src/mlpack/bindings/python/setup.py.in
Labels: c: automatic bindings, c: build system, s: needs review, t: bugfix

#2150 doc: fixed variable name issue & added header files
  doc/tutorials/ann/ann.txt
Labels: c: documentation, c: methods, s: needs review, t: bugfix

#2155 correct softsign equation in document
  src/mlpack/methods/ann/activation_functions/softsign_function.hpp
Labels: c: documentation, s: needs review

#2158 Addition of Mish Activation Function (Issue : #2156)
  .ci/windows-steps.yaml
  COPYRIGHT.txt
  src/mlpack/methods/ann/activation_functions/CMakeLists.txt
  src/mlpack/methods/ann/activation_functions/mish_function.hpp
  src/mlpack/methods/ann/layer/base_layer.hpp
  src/mlpack/methods/ann/layer/transposed_convolution.hpp
  src/mlpack/methods/ann/layer/transposed_convolution_impl.hpp
  src/mlpack/tests/activation_functions_test.cpp
  src/mlpack/tests/ann_layer_test.cpp
Labels: c: methods, s: needs review, t: added feature
