Repository mlpack/mlpack, pull requests merged in 2021-04, with the labels that each got.

#2899 Fix Go-bindings flow control nesting.
  CMake/go/AppendModel.cmake
Labels: c: automatic bindings, t: bugfix

#2896 Fix LazyData Note in R-bindings.
  src/mlpack/bindings/R/mlpack/DESCRIPTION.in
Labels: c: automatic bindings, t: bugfix

#2887 Fixed mean poolinglayer for correct ceil_mode
  src/mlpack/methods/ann/layer/mean_pooling.hpp
  src/mlpack/methods/ann/layer/mean_pooling_impl.hpp
  src/mlpack/tests/ann_layer_test.cpp
Labels: c: methods, t: bugfix

#2909 fix typo in rl tutorial
  doc/tutorials/reinforcement_learning/reinforcement_learning.txt
Labels: c: documentation

#2881 Added warm start feature to Random Forest.
  HISTORY.md
  src/mlpack/methods/random_forest/random_forest.hpp
  src/mlpack/methods/random_forest/random_forest_impl.hpp
  src/mlpack/methods/random_forest/random_forest_main.cpp
  src/mlpack/tests/main_tests/random_forest_test.cpp
  src/mlpack/tests/random_forest_test.cpp
Labels: c: methods, t: added feature

#2913 Fixed ResetParameters() in #2855
  COPYRIGHT.txt
  src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp
Labels: t: bugfix

#2918 Include string header to resolve undefined type error
  src/mlpack/tests/main_tests/gmm_generate_test.cpp
  src/mlpack/tests/main_tests/gmm_probability_test.cpp
  src/mlpack/tests/main_tests/range_search_test.cpp
Labels: c: testing, t: bugfix

#2901 Refactor tests to use approx_equal()
  src/mlpack/tests/ann_dist_test.cpp
Labels: c: testing

#2928 Download all boost instead of a specific version.
  .ci/linux-steps.yaml
Labels: c: build system

#2927 The Autodownloader.
  CMake/Autodownload.cmake
  CMakeLists.txt
Labels: c: build system, t: added feature

#2929 Fix find armadillo by rcurtin.
  CMake/FindArmadillo.cmake
Labels: c: build system, t: bugfix

#2925 Test config
  src/mlpack/tests/CMakeLists.txt
Labels: c: build system

#2930 Fix cover tree issues by @rcurtin fixes #2869
  src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp
  src/mlpack/core/tree/cover_tree/dual_tree_traverser_impl.hpp
  src/mlpack/core/tree/cover_tree/single_tree_traverser_impl.hpp
  src/mlpack/tests/akfn_test.cpp
  src/mlpack/tests/krann_search_test.cpp
Labels: c: methods, t: bugfix

#2926 Don't build mlpack_test as part of make.
  .ci/linux-steps.yaml
  .ci/macos-steps.yaml
  .ci/windows-steps.yaml
  .github/workflows/main.yml
  HISTORY.md
  README.md
  doc/guide/build.hpp
  src/mlpack/tests/CMakeLists.txt
Labels: c: build system, c: testing, t: added feature

#2908 Solve static code analysis issues
  src/mlpack/bindings/go/print_doc_functions_impl.hpp
  src/mlpack/core/kernels/epanechnikov_kernel_impl.hpp
  src/mlpack/core/kernels/spherical_kernel.hpp
  src/mlpack/core/metrics/bleu_impl.hpp
  src/mlpack/core/tree/rectangle_tree/x_tree_split_impl.hpp
  src/mlpack/methods/amf/termination_policies/simple_tolerance_termination.hpp
  src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression.cpp
  src/mlpack/methods/cf/cf_model.cpp
  src/mlpack/methods/det/dtree_impl.hpp
  src/mlpack/methods/fastmks/fastmks_main.cpp
  src/mlpack/methods/linear_svm/linear_svm_main.cpp
  src/mlpack/methods/neighbor_search/neighbor_search_rules_impl.hpp
  src/mlpack/tests/det_test.cpp
  src/mlpack/tests/serialization.hpp
Labels: c: testing

#2931 If we are building mlpack statically then build executable statically
  README.md
  doc/guide/build.hpp
  src/mlpack/bindings/cli/CMakeLists.txt
  src/mlpack/tests/CMakeLists.txt
Labels: c: build system

#2935 Add a link to the vision document in the readme
  README.md
Labels: c: documentation
