Repository mlpack/mlpack, pull requests merged in 2021-11, with the labels that each got.

#3080 Fix comments in files that implement SVD methods for PCA
  COPYRIGHT.txt
  src/mlpack/methods/pca/decomposition_policies/exact_svd_method.hpp
  src/mlpack/methods/pca/decomposition_policies/quic_svd_method.hpp
  src/mlpack/methods/pca/decomposition_policies/randomized_block_krylov_method.hpp
  src/mlpack/methods/pca/decomposition_policies/randomized_svd_method.hpp
Labels: c: documentation

#3076 Disable auto-download by default + improve test stability
  .ci/ci.yaml
  .ci/linux-steps.yaml
  .ci/windows-steps.yaml
  .github/workflows/main.yml
  CMakeLists.txt
  src/mlpack/methods/ann/layer/convolution_impl.hpp
  src/mlpack/tests/cf_test.cpp
  src/mlpack/tests/decision_tree_regressor_test.cpp
  src/mlpack/tests/gmm_test.cpp
  src/mlpack/tests/linear_svm_test.cpp
  src/mlpack/tests/logistic_regression_test.cpp
  src/mlpack/tests/main_tests/image_converter_test.cpp
  src/mlpack/tests/nmf_test.cpp
  src/mlpack/tests/q_learning_test.cpp
Labels: c: build system

#3084 Create variable using MatType instead of arma::mat
  src/mlpack/methods/linear_svm/linear_svm_function_impl.hpp
Labels: c: methods, t: bugfix

#3081 Make R bindings depend on `pkgbuild`
  CMake/FindRModule.cmake
  HISTORY.md
  src/mlpack/bindings/R/CMakeLists.txt
Labels: c: build system, c: automatic bindings, t: bugfix

#2942 Adapting armadillo's parser for mlpack(Removing Boost Dependencies)
  doc/tutorials/data_loading/datasetmapper.txt
  doc/tutorials/tutorials.txt
  src/mlpack/core/data/CMakeLists.txt
  src/mlpack/core/data/detect_file_type.cpp
  src/mlpack/core/data/detect_file_type.hpp
  src/mlpack/core/data/load.cpp
  src/mlpack/core/data/load.hpp
  src/mlpack/core/data/load_arff_impl.hpp
  src/mlpack/core/data/load_categorical_csv.hpp
  src/mlpack/core/data/load_csv.cpp
  src/mlpack/core/data/load_csv.hpp
  src/mlpack/core/data/load_impl.hpp
  src/mlpack/core/data/load_numeric_csv.hpp
  src/mlpack/core/data/save.hpp
  src/mlpack/core/data/save_impl.hpp
  src/mlpack/core/data/string_algorithms.hpp
  src/mlpack/core/data/types.hpp
  src/mlpack/core/data/types_impl.hpp
  src/mlpack/tests/load_save_test.cpp
Labels: c: core, update dependencies

#3057 Update logistic regression documentation to be agnostic for class values
  src/mlpack/bindings/R/mlpack_main.hpp
  src/mlpack/bindings/cli/mlpack_main.hpp
  src/mlpack/bindings/go/mlpack_main.hpp
  src/mlpack/bindings/julia/mlpack_main.hpp
  src/mlpack/bindings/markdown/mlpack_main.hpp
  src/mlpack/bindings/python/mlpack_main.hpp
  src/mlpack/bindings/tests/mlpack_main.hpp
  src/mlpack/methods/logistic_regression/logistic_regression_main.cpp
Labels: c: binding, c: documentation, t: bugfix

#3050 Replace boost::math::special_functions
  src/mlpack/core/CMakeLists.txt
  src/mlpack/core/boost_backport/CMakeLists.txt
  src/mlpack/core/boost_backport/LICENSE.txt
  src/mlpack/core/boost_backport/README.md
  src/mlpack/core/boost_backport/bernoulli.hpp
  src/mlpack/core/boost_backport/detail/bernoulli_details.hpp
  src/mlpack/core/boost_backport/detail/polygamma.hpp
  src/mlpack/core/boost_backport/detail/unchecked_bernoulli.hpp
  src/mlpack/core/boost_backport/math_fwd.hpp
  src/mlpack/core/boost_backport/policy.hpp
  src/mlpack/core/dists/gamma_distribution.cpp
  src/mlpack/core/dists/gamma_distribution.hpp
  src/mlpack/core/math/CMakeLists.txt
  src/mlpack/core/math/digamma.hpp
  src/mlpack/core/math/trigamma.hpp
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/data/digamma_data.csv
  src/mlpack/tests/data/digamma_neg_data.csv
  src/mlpack/tests/data/digamma_root_data.csv
  src/mlpack/tests/data/digamma_small_data.csv
  src/mlpack/tests/data/trigamma_data.csv
  src/mlpack/tests/digamma_test.cpp
  src/mlpack/tests/trigamma_test.cpp
Labels: c: methods, update dependencies

#3088 Fix compilation options for MinGW
  CMakeLists.txt
Labels: c: build system, t: bugfix

#3058 Remove deprecated options for logistic regression
  src/mlpack/methods/logistic_regression/logistic_regression_main.cpp
  src/mlpack/tests/main_tests/logistic_regression_test.cpp
Labels: c: binding, t: bugfix
