Repository mlpack/mlpack, pull requests merged in 2022-10, with the labels that each got.

#3282 Handle MaxPooling index computation for identical elements
  src/mlpack/methods/ann/layer/max_pooling.hpp
Labels: c: methods, t: bugfix

#3287 update to catch v2.13.10
  src/mlpack/tests/catch.hpp
Labels: c: testing, t: bugfix, update dependencies

#3290 Fix Markdown sidebar anchors
  src/mlpack/bindings/markdown/CMakeLists.txt
  src/mlpack/bindings/markdown/generate_markdown.binding.cpp.in
  src/mlpack/bindings/markdown/generate_markdown.binding.hpp.in
  src/mlpack/bindings/markdown/get_binding_name.cpp
  src/mlpack/bindings/markdown/get_binding_name.hpp
  src/mlpack/bindings/markdown/print_docs.cpp
Labels: c: documentation, t: bugfix

#3292 Fix release script
  scripts/release-mlpack.sh
Labels: c: build system, t: bugfix

#3291 Fix Windows example
  doc/examples/sample-ml-app/README.txt
  doc/examples/sample-ml-app/sample-ml-app/sample-ml-app.cpp
  doc/examples/sample-ml-app/sample-ml-app/sample-ml-app.vcxproj
  doc/user/sample_ml_app.md
Labels: c: documentation, t: bugfix

#3296 Move R Github Actions workflow to r-lib/actions@v2
  .github/workflows/main.yml
Labels: c: build system, s: unanswered

#3299 Remove Doxygen links.
  README.md
Labels: c: documentation, t: bugfix

#3294 Update CMake usage in build instructions
  README.md
Labels: s: needs review, c: build system, c: documentation
