Repository mlpack/mlpack, pull requests merged in 2022-09, with the labels that each got.

#3267 Switch from bitwise to logical comparison
  src/mlpack/core/tree/rectangle_tree/x_tree_split_impl.hpp
Labels: c: methods, t: bugfix

#3268 Don't use alias in `Adaboost::Classify()`
  src/mlpack/methods/adaboost/adaboost_impl.hpp
Labels: c: methods, t: bugfix

#3264 Add vcpkg installation instructions
  doc/quickstart/cpp.md
Labels: s: unanswered, s: unlabeled

#3263 GitHub Workflows security hardening
  .github/workflows/main.yml
Labels: s: unanswered, s: unlabeled

#3271 avoid deprecation warnings in Armadillo 11.2+
  src/mlpack/tests/ann/layer/add_merge.cpp
  src/mlpack/tests/ann/layer/batch_norm.cpp
  src/mlpack/tests/ann/layer/mean_pooling.cpp
Labels: c: testing

#3277 Fix -Wpedantic
  COPYRIGHT.txt
  src/mlpack/core/tree/space_split/hyperplane.hpp
  src/mlpack/core/tree/space_split/projection_vector.hpp
  src/mlpack/core/util/sfinae_utility.hpp
Labels: c: core, t: bugfix

#3278 Remove `RangeType` change comment (attempt #2)
  src/mlpack/core/math/range.hpp
Labels: c: core

#3279 Actually install `namespace_compat.hpp`
  src/mlpack/CMakeLists.txt
Labels: c: build system, t: bugfix

#3276 Don't set `strict` for aliases in bindings.
  src/mlpack/bindings/go/mlpack/capi/arma_util.cpp
  src/mlpack/bindings/go/mlpack/capi/io_util.cpp
  src/mlpack/bindings/go/tests/go_binding_test.go
  src/mlpack/bindings/julia/julia_util.cpp
  src/mlpack/bindings/julia/julia_util.h
  src/mlpack/bindings/julia/mlpack/params.jl.in
  src/mlpack/bindings/julia/print_input_processing_impl.hpp
  src/mlpack/bindings/julia/print_jl.cpp
  src/mlpack/bindings/julia/print_output_processing_impl.hpp
  src/mlpack/bindings/julia/print_param_defn.hpp
  src/mlpack/bindings/julia/tests/runtests.jl
Labels: c: automatic bindings, t: bugfix
