Repository mlpack/mlpack, pull requests merged in 2022-04, with the labels that each got.

#3153 Check if atomics need `-latomic` linking.
  CMake/CheckAtomic.cmake
  CMakeLists.txt
Labels: s: stale, t: bugfix

#3091 mlpack Header only initiative
  CMake/TestStaticSTB.cmake
  CMake/stb/a.cpp
  CMake/stb/a.hpp
  CMake/stb/b.cpp
  CMake/stb/b.hpp
  CMake/stb/main.cpp
  CMakeLists.txt
  src/mlpack/core/data/CMakeLists.txt
  src/mlpack/core/data/detect_file_type.hpp
  src/mlpack/core/data/detect_file_type_impl.hpp
  src/mlpack/core/data/image_info_impl.hpp
  src/mlpack/core/data/load.hpp
  src/mlpack/core/data/load_image.cpp
  src/mlpack/core/data/load_image.hpp
  src/mlpack/core/data/load_image_impl.hpp
  src/mlpack/core/data/load_impl.hpp
  src/mlpack/core/data/save.hpp
  src/mlpack/core/data/save_image.hpp
  src/mlpack/core/data/save_image_impl.hpp
  src/mlpack/core/data/save_impl.hpp
  src/mlpack/core/kernels/CMakeLists.txt
  src/mlpack/core/kernels/epanechnikov_kernel.cpp
  src/mlpack/core/kernels/epanechnikov_kernel.hpp
  src/mlpack/core/kernels/epanechnikov_kernel_impl.hpp
  src/mlpack/core/kernels/pspectrum_string_kernel.cpp
  src/mlpack/core/kernels/pspectrum_string_kernel.hpp
  src/mlpack/core/kernels/pspectrum_string_kernel_impl.hpp
  src/mlpack/core/math/CMakeLists.txt
  src/mlpack/core/math/lin_alg.cpp
  src/mlpack/core/math/lin_alg.hpp
  src/mlpack/core/math/lin_alg_impl.hpp
  src/mlpack/core/math/random_basis.hpp
  src/mlpack/core/math/random_basis_impl.hpp
  src/mlpack/methods/ann/init_rules/gaussian_init.hpp
  src/mlpack/methods/ann/init_rules/glorot_init.hpp
  src/mlpack/methods/ann/layer_names.hpp
  src/mlpack/methods/cf/cf_main.cpp
  src/mlpack/methods/det/dtree_impl.hpp
  src/mlpack/methods/gmm/gmm_generate_main.cpp
  src/mlpack/methods/gmm/gmm_train_main.cpp
  src/mlpack/methods/hmm/hmm_util_impl.hpp
  src/mlpack/methods/kmeans/kmeans_main.cpp
  src/mlpack/methods/linear_svm/linear_svm_main.cpp
  src/mlpack/methods/lmnn/lmnn_main.cpp
  src/mlpack/methods/lsh/lsh_main.cpp
  src/mlpack/methods/nca/nca_main.cpp
  src/mlpack/methods/neighbor_search/kfn_main.cpp
  src/mlpack/methods/neighbor_search/knn_main.cpp
  src/mlpack/methods/nmf/nmf_main.cpp
  src/mlpack/methods/preprocess/preprocess_scale_main.cpp
  src/mlpack/methods/preprocess/preprocess_split_main.cpp
  src/mlpack/methods/random_forest/random_forest_main.cpp
  src/mlpack/methods/range_search/range_search_main.cpp
  src/mlpack/methods/rann/krann_main.cpp
  src/mlpack/methods/reinforcement_learning/q_networks/categorical_dqn.hpp
  src/mlpack/methods/reinforcement_learning/q_networks/dueling_dqn.hpp
  src/mlpack/methods/reinforcement_learning/q_networks/simple_dqn.hpp
Labels: c: methods, t: added feature

#3190 Add weighted data constructor to `Perceptron`
  COPYRIGHT.txt
  HISTORY.md
  src/mlpack/methods/perceptron/perceptron.hpp
  src/mlpack/methods/perceptron/perceptron_impl.hpp
  src/mlpack/tests/cv_test.cpp
  src/mlpack/tests/perceptron_test.cpp
Labels: c: methods, t: bugfix

#3199 R Build Fix
  .github/workflows/main.yml
Labels: t: bugfix

#3198 Python Build Fix
  src/mlpack/bindings/python/copy_artifacts.py
Labels: t: bugfix
