Repository mlpack/mlpack, pull requests merged in 2022-12, with the labels that each got.

#3328 Update RcppArmadillo header locations
  src/mlpack/bindings/R/mlpack/inst/include/mlpack.h.in
  src/mlpack/bindings/R/mlpack/src/rcpp_mlpack.h
Labels: c: automatic bindings

#3330 Fix ANN tutorial documentation
  doc/tutorials/ann.md
  doc/tutorials/res/ann.gv
  doc/tutorials/res/ann.svg
Labels: c: documentation, t: bugfix

#3334 Improving ann doc
  doc/tutorials/ann.md
Labels: c: documentation, t: bugfix

#3327 Fix binding handling of transposed matrix parameters
  HISTORY.md
  src/mlpack/bindings/R/mlpack/src/r_util.cpp
  src/mlpack/bindings/R/mlpack/tests/testthat/test-R_binding.R
  src/mlpack/bindings/R/print_input_processing.hpp
  src/mlpack/bindings/R/tests/test_r_binding_main.cpp
  src/mlpack/bindings/go/CMakeLists.txt
  src/mlpack/bindings/go/mlpack/arma_util.go
  src/mlpack/bindings/go/mlpack/capi/arma_util.cpp
  src/mlpack/bindings/go/mlpack/capi/arma_util.h
  src/mlpack/bindings/go/print_input_processing.hpp
  src/mlpack/bindings/go/tests/go_binding_test.go
  src/mlpack/bindings/go/tests/test_go_binding_main.cpp
  src/mlpack/bindings/julia/mlpack/params.jl.in
  src/mlpack/bindings/julia/print_input_processing_impl.hpp
  src/mlpack/bindings/julia/tests/runtests.jl
  src/mlpack/bindings/julia/tests/test_julia_binding_main.cpp
  src/mlpack/bindings/python/CMakeLists.txt
  src/mlpack/bindings/python/mlpack/io.pxd
  src/mlpack/bindings/python/mlpack/io_util.hpp
  src/mlpack/bindings/python/mlpack/matrix_utils.py
  src/mlpack/bindings/python/print_input_processing.hpp
  src/mlpack/bindings/python/tests/test_python_binding.py
  src/mlpack/bindings/python/tests/test_python_binding_main.cpp
Labels: c: automatic bindings, t: bugfix

#3331 Remove last references to doxygen in the documentation.
  doc/developer/bindings.md
  doc/quickstart/cpp.md
Labels: c: documentation, t: bugfix

#3332 Use a conditional to disable the Catch update job instead
  .github/workflows/update-catch.yaml
Labels: t: bugfix

#3335 fix internal links in README.md
  README.md
Labels: c: documentation, s: unanswered, t: bugfix

#3322 comment out definition of ARMA_NO_DEBUG
  CMakeLists.txt
  HISTORY.md
Labels: c: build system

#3337 input to input_ in python quickstart
  COPYRIGHT.txt
  doc/quickstart/python.md
Labels: s: unanswered, s: unlabeled
