Repository mlpack/mlpack, pull requests merged in 2023-06, with the labels that each got.

#3488 Install mlpack and cereal headers in R package
  HISTORY.md
  src/mlpack/bindings/R/CMakeLists.txt
  src/mlpack/bindings/R/mlpack/src/Makevars
  src/mlpack/bindings/R/mlpack/src/Makevars.win
  src/mlpack/tests/nmf_test.cpp
Labels: c: automatic bindings, t: bugfix

#3490 Document the use of std::move() to avoid copies for neural networks
  src/mlpack/methods/ann/ffn.hpp
  src/mlpack/methods/ann/ffn_impl.hpp
  src/mlpack/methods/ann/rnn.hpp
  src/mlpack/methods/ann/rnn_impl.hpp
Labels: c: documentation, t: bugfix

#3493 LARS fixes: intercept, normalization, bugfix
  HISTORY.md
  src/mlpack/core/math/lin_alg.hpp
  src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression_main.cpp
  src/mlpack/methods/lars/lars.hpp
  src/mlpack/methods/lars/lars_impl.hpp
  src/mlpack/methods/lars/lars_main.cpp
  src/mlpack/methods/local_coordinate_coding/lcc_impl.hpp
  src/mlpack/methods/sparse_coding/sparse_coding_impl.hpp
  src/mlpack/tests/data/lars_kkt.bin
  src/mlpack/tests/lars_test.cpp
Labels: c: methods, t: bugfix, t: added feature

#3497 Add missing file to git commit for release script
  scripts/release-mlpack.sh
Labels: t: bugfix

#3494 Reinforcement Learning: Deep Deterministic Policy Gradient
  HISTORY.md
  src/mlpack/methods/reinforcement_learning/ddpg.hpp
  src/mlpack/methods/reinforcement_learning/ddpg_impl.hpp
  src/mlpack/methods/reinforcement_learning/reinforcement_learning.hpp
  src/mlpack/tests/q_learning_test.cpp
Labels: c: methods, t: added feature

#3504 Update R package description to more recent mlpack 4 paper
  src/mlpack/bindings/R/mlpack/DESCRIPTION.in
Labels: c: documentation, t: bugfix

#3502 fix: append existing PYTHONPATH to CMAKE_PYTHON_PATH
  src/mlpack/bindings/python/CMakeLists.txt
Labels: s: unanswered, s: unlabeled
