Repository mlpack/mlpack, pull requests merged in 2023-12, with the labels that each got.

#3554 feat: add accuracy measure for mlpack_logistic_regression
  HISTORY.md
  src/mlpack/methods/logistic_regression/logistic_regression_main.cpp
  src/mlpack/tests/main_tests/logistic_regression_test.cpp
Labels: s: needs review, c: binding, t: added feature

#3575 Fix documentation for `MultiheadAttention`
  src/mlpack/methods/ann/layer/multihead_attention.hpp
Labels: c: documentation, t: bugfix

#3570 Remove no-longer-needed round() implementation for MSVC
  HISTORY.md
  src/mlpack/core/math/math.hpp
  src/mlpack/core/math/round.hpp
Labels: c: core, t: bugfix

#3579 Add include files and configured pkgconfig file to Python distribution
  CMake/ConfigureFileOnly.cmake
  src/mlpack/bindings/python/CMakeLists.txt
  src/mlpack/bindings/python/mlpack.pc.in
  src/mlpack/bindings/python/setup.py.in
Labels: c: build system, c: automatic bindings, t: added feature

#3582 Fix flaky `IncrementalTrainingTest`
  src/mlpack/tests/perceptron_test.cpp
Labels: c: testing, t: bugfix

#3578 Document `BayesianLinearRegression`
  doc/user/methods/bayesian_linear_regression.md
  src/mlpack/core/util/arma_traits.hpp
  src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression.hpp
  src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression_impl.hpp
  src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression_main.cpp
  src/mlpack/tests/bayesian_linear_regression_test.cpp
  src/mlpack/tests/main_tests/bayesian_linear_regression_test.cpp
  src/mlpack/tests/serialization_test.cpp
Labels: c: documentation, t: added feature

#3587 Fix python test duplicate filename error
  src/mlpack/bindings/python/CMakeLists.txt
Labels: c: build system, c: automatic bindings, t: bugfix

#3577 Document `LinearSVM`
  doc/user/methods/linear_svm.md
  src/mlpack/core/util/ens_traits.hpp
  src/mlpack/methods/linear_svm/linear_svm.hpp
  src/mlpack/methods/linear_svm/linear_svm_function.hpp
  src/mlpack/methods/linear_svm/linear_svm_function_impl.hpp
  src/mlpack/methods/linear_svm/linear_svm_impl.hpp
  src/mlpack/methods/linear_svm/linear_svm_main.cpp
  src/mlpack/tests/linear_svm_test.cpp
Labels: c: documentation, t: added feature

#3572 Document `HoeffdingTree`
  doc/user/methods/hoeffding_tree.md
  src/mlpack/methods/hoeffding_trees/hoeffding_numeric_split.hpp
  src/mlpack/methods/hoeffding_trees/hoeffding_tree.hpp
  src/mlpack/methods/hoeffding_trees/hoeffding_tree_impl.hpp
  src/mlpack/methods/hoeffding_trees/hoeffding_tree_model_impl.hpp
  src/mlpack/tests/hoeffding_tree_test.cpp
Labels: c: documentation, c: methods, t: added feature
