Repository mlpack/mlpack, pull requests merged in 2023-09, with the labels that each got.

#3520 Reinforcement Learning: Introducing Agent-Specific Tutorials
  doc/tutorials/reinforcement_learning.md
  doc/tutorials/reinforcement_learning/asynchronous_learning.md
  doc/tutorials/reinforcement_learning/ddpg.md
  doc/tutorials/reinforcement_learning/q_learning.md
  doc/tutorials/reinforcement_learning/sac.md
  doc/tutorials/reinforcement_learning/td3.md
Labels: c: documentation, t: added feature

#3532 Fix Windows Azure MSI build and loosen some test tolerances
  .ci/windows-steps.yaml
  src/mlpack/tests/cf_test.cpp
Labels: c: build system, t: bugfix

#3533 Release version 4.2.1
  HISTORY.md
  README.md
  doc/examples/sample-ml-app/README.txt
  doc/examples/sample-ml-app/sample-ml-app/sample-ml-app.vcxproj
  doc/user/sample_ml_app.md
  src/mlpack/core/util/version.hpp
Labels: t: release

#3534 Float -- episode 1
  src/mlpack/methods/ann/ffn_impl.hpp
  src/mlpack/methods/ann/layer/batch_norm_impl.hpp
  src/mlpack/methods/ann/layer/c_relu_impl.hpp
  src/mlpack/methods/ann/layer/convolution.hpp
  src/mlpack/methods/ann/layer/convolution_impl.hpp
  src/mlpack/methods/ann/layer/grouped_convolution.hpp
  src/mlpack/methods/ann/layer/grouped_convolution_impl.hpp
  src/mlpack/methods/ann/layer/leaky_relu.hpp
  src/mlpack/methods/ann/layer/leaky_relu_impl.hpp
  src/mlpack/methods/ann/layer/mean_pooling_impl.hpp
Labels: c: methods
