Repository mlpack/mlpack, pull requests merged in 2023-10, with the labels that each got.

#3538 Fix Random Forest Test
  src/mlpack/tests/random_forest_test.cpp
Labels: c: testing, t: bugfix

#3541 Fix include ordering for `LinearRegression`
  HISTORY.md
  src/mlpack/core/dists/regression_distribution.hpp
  src/mlpack/core/dists/regression_distribution_impl.hpp
  src/mlpack/methods/linear_regression/linear_regression.hpp
Labels: c: methods, t: bugfix

#3545 Fix L1 regularization in case where weight is zero
  HISTORY.md
  src/mlpack/methods/ann/regularizer/lregularizer_impl.hpp
Labels: c: methods, t: bugfix

#3543 Another cran fix round two
  HISTORY.md
  src/mlpack/bindings/R/mlpack/R/package.R
Labels: c: automatic bindings, t: bugfix

#3546 ANN Layers Template Parameter Consistency
  src/mlpack/methods/ann/ffn_impl.hpp
  src/mlpack/methods/ann/layer/leaky_relu_impl.hpp
Labels: s: unlabeled

#3550 Use HTTPS for auto-downloaded dependencies
  CMakeLists.txt
  HISTORY.md
Labels: c: build system

#3555 detect C++17 mode in MSVC
  HISTORY.md
  src/mlpack/base.hpp
Labels: c: core
