Repository mlpack/mlpack, pull requests merged in 2023-02, with the labels that each got.

#3393 update citation details
  README.md
Labels: c: documentation

#3346 Fix DBSCAN handling of non-core points
  HISTORY.md
  src/mlpack/methods/dbscan/dbscan_impl.hpp
  src/mlpack/tests/dbscan_test.cpp
Labels: c: methods, t: bugfix

#3400 Redundant Documentation
  doc/developer/bindings.md
  src/mlpack/core/util/param.hpp
Labels: c: documentation, t: bugfix

#3405 avoid deprecation warnings in Armadillo 11.4.4+
  HISTORY.md
  src/mlpack/core/data/save_impl.hpp
  src/mlpack/tests/load_save_test.cpp
Labels: c: testing, c: core

#3398 Update outdated codes in cf.md and datasetmapper.md
  HISTORY.md
  doc/tutorials/cf.md
  doc/tutorials/datasetmapper.md
  src/mlpack/methods/cf/cf.hpp
Labels: c: documentation, t: bugfix

#3408 [R] Set compilation standard to C++17 on Windows, remove it on Unix (Closes #3407)
  src/mlpack/bindings/R/mlpack/src/Makevars
  src/mlpack/bindings/R/mlpack/src/Makevars.win
Labels: s: unanswered, s: unlabeled

#3409 Transfer Randomized svd implementation from .hpp to *impl.hpp
  src/mlpack/methods/randomized_svd/randomized_svd.hpp
  src/mlpack/methods/randomized_svd/randomized_svd_impl.hpp
Labels: c: methods

#3401 Fix codes and improve doc
  doc/tutorials/approx_kfn.md
  doc/tutorials/fastmks.md
Labels: c: documentation, t: bugfix

#3416 Update date
  LICENSE.txt
Labels: s: unanswered, s: unlabeled

#3411 Possible fixes
  doc/tutorials/amf.md
  doc/tutorials/linear_regression.md
  src/mlpack/bindings/markdown/print_param_table.hpp
  src/mlpack/bindings/python/print_wrapper_py.cpp
  src/mlpack/core/util/param.hpp
  src/mlpack/core/util/params_impl.hpp
  src/mlpack/methods/svdplusplus/svdplusplus.hpp
Labels: s: needs review, c: documentation

#3415 [R] Remove configure script as sunos is no longer an issue
  src/mlpack/bindings/R/CMakeLists.txt
  src/mlpack/bindings/R/mlpack/configure
Labels: c: automatic bindings

#3421 Fix function name
  doc/tutorials/image.md
Labels: s: unanswered, s: unlabeled

#3404 Add Quic_SVD method in CF
  src/mlpack/methods/cf/decomposition_policies/decomposition_policies.hpp
  src/mlpack/methods/cf/decomposition_policies/quic_svd_method.hpp
  src/mlpack/methods/quic_svd/quic_svd.hpp
  src/mlpack/methods/quic_svd/quic_svd_impl.hpp
  src/mlpack/tests/cf_test.cpp
Labels: s: unanswered, s: unlabeled

#3413 Add Block Krylov SVD method in CF
  doc/tutorials/cf.md
  src/mlpack/methods/cf/cf_main.cpp
  src/mlpack/methods/cf/cf_model.hpp
  src/mlpack/methods/cf/cf_model_impl.hpp
  src/mlpack/methods/cf/decomposition_policies/block_krylov_svd_method.hpp
  src/mlpack/methods/cf/decomposition_policies/decomposition_policies.hpp
  src/mlpack/tests/cf_test.cpp
Labels: s: unanswered, s: unlabeled

#3414 Update HISTORY.md
  HISTORY.md
Labels: s: unanswered, s: unlabeled
