Repository mlpack/mlpack, pull requests merged in 2024-09, with the labels that each got.

#3788 Update MSI installer to include mlpack.hpp and Markdown documentation
  .ci/windows-steps.yaml
  scripts/build-docs.sh
Labels: c: build system, t: bugfix

#3792 Split core.md into multiple pages
  doc/developer/distances.md
  doc/developer/kernels.md
  doc/index.md
  doc/sidebar.html
  doc/user/core.md
  doc/user/core/distances.md
  doc/user/core/distributions.md
  doc/user/core/kernels.md
  doc/user/core/math.md
  doc/user/methods/linear_svm.md
  doc/user/methods/lmnn.md
  doc/user/methods/mean_shift.md
  doc/user/methods/naive_bayes_classifier.md
  doc/user/methods/nca.md
  scripts/build-docs.sh
Labels: c: documentation

#3787 Document `Radical`
  HISTORY.md
  doc/index.md
  doc/sidebar.html
  doc/user/bindings/cli.md
  doc/user/bindings/go.md
  doc/user/bindings/julia.md
  doc/user/bindings/python.md
  doc/user/bindings/r.md
  doc/user/methods/pca.md
  doc/user/methods/radical.md
  src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression_main.cpp
  src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp
  src/mlpack/methods/lars/lars_main.cpp
  src/mlpack/methods/linear_regression/linear_regression_main.cpp
  src/mlpack/methods/linear_svm/linear_svm_main.cpp
  src/mlpack/methods/lmnn/lmnn_main.cpp
  src/mlpack/methods/logistic_regression/logistic_regression_main.cpp
  src/mlpack/methods/mean_shift/mean_shift_main.cpp
  src/mlpack/methods/naive_bayes/nbc_main.cpp
  src/mlpack/methods/nca/nca_main.cpp
  src/mlpack/methods/nmf/nmf_main.cpp
  src/mlpack/methods/pca/pca_main.cpp
  src/mlpack/methods/perceptron/perceptron_main.cpp
  src/mlpack/methods/radical/radical.hpp
  src/mlpack/methods/radical/radical_impl.hpp
  src/mlpack/methods/radical/radical_main.cpp
  src/mlpack/methods/random_forest/random_forest_main.cpp
  src/mlpack/methods/softmax_regression/softmax_regression_main.cpp
  src/mlpack/methods/sparse_coding/sparse_coding_main.cpp
  src/mlpack/tests/radical_test.cpp
Labels: c: documentation, t: added feature

#3764 Optimize Elkan K-means with OpenMP
  src/mlpack/methods/kmeans/elkan_kmeans_impl.hpp
Labels: s: keep open

#3799 Fix compilation errors with clang 19
  COPYRIGHT.txt
  HISTORY.md
  src/mlpack/core/tree/octree/octree_impl.hpp
Labels: c: core, t: bugfix

#3794 Document `KDTree` and `BinarySpaceTree` and related classes
  doc/developer/trees.md
  doc/img/hrectbound.png
  doc/sidebar.html
  doc/user/core.md
  doc/user/core/kernels.md
  doc/user/core/trees.md
  doc/user/core/trees/binary_space_tree.md
  doc/user/core/trees/kdtree.md
  scripts/build-docs.sh
  scripts/test-docs.sh
  src/mlpack/core/tree/binary_space_tree/binary_space_tree.hpp
  src/mlpack/core/tree/binary_space_tree/binary_space_tree_impl.hpp
  src/mlpack/core/tree/binary_space_tree/midpoint_split.hpp
  src/mlpack/core/tree/binary_space_tree/typedef.hpp
  src/mlpack/core/tree/hrectbound.hpp
  src/mlpack/core/tree/hrectbound_impl.hpp
Labels: c: documentation, t: added feature
