Repository mlpack/mlpack, pull requests merged in 2024-03, with the labels that each got.

#3644 Handle adjacent floating-point values in `BestBinaryNumericSplit`
  HISTORY.md
  src/mlpack/methods/decision_tree/best_binary_numeric_split_impl.hpp
Labels: c: methods, t: bugfix

#3651 BUG Fix RandNormal() to take the standard deviation as a parameter instead of the variance
  doc/user/core.md
  src/mlpack/core/math/random.hpp
  src/mlpack/methods/ann/init_rules/gaussian_init.hpp
  src/mlpack/methods/ann/init_rules/glorot_init.hpp
  src/mlpack/methods/reinforcement_learning/noise/gaussian.hpp
  src/mlpack/tests/ann/not_adapted/gan_test.cpp
  src/mlpack/tests/policy_gradient_test.cpp
Labels: t: bugfix

#3652 Add automatically-generated sidebar for documentation
  README.md
  doc/css/gfm-mod.css
  doc/css/rouge-github-mod.css
  doc/developer/bindings.md
  doc/developer/trees.md
  doc/img/favicons-blocks.png
  doc/img/favicons-matrix.png
  doc/index.md
  doc/sidebar.html
  doc/tutorials/ann.md
  doc/user/build_windows.md
  doc/user/core.md
  doc/user/formats.md
  doc/user/load_save.md
  doc/user/matrices.md
  doc/user/methods/adaboost.md
  doc/user/methods/bayesian_linear_regression.md
  doc/user/methods/decision_tree.md
  doc/user/methods/decision_tree_regressor.md
  doc/user/methods/hoeffding_tree.md
  doc/user/methods/lars.md
  doc/user/methods/linear_regression.md
  doc/user/methods/linear_svm.md
  doc/user/methods/logistic_regression.md
  doc/user/methods/naive_bayes_classifier.md
  doc/user/methods/perceptron.md
  doc/user/methods/random_forest.md
  doc/user/methods/softmax_regression.md
  scripts/README.md
  scripts/build-docs.sh
  scripts/release-mlpack.sh
  scripts/test-docs.sh
Labels: c: documentation, t: added feature

#3660 Fix STB detection when STB is manually specified
  CMake/FindStbImage.cmake
  CMakeLists.txt
Labels: c: build system, t: bugfix

#3661 Fix name of package in Debian/Ubuntu
  doc/quickstart/cpp.md
Labels: c: documentation, t: bugfix

#3665 catch2 workaround for recent issue under macOS
  src/mlpack/tests/catch.hpp
Labels: c: testing, t: bugfix

#3668 Changes to binding.md
  doc/developer/bindings.md
Labels: s: unanswered, s: unlabeled
