Repository mlpack/mlpack, pull requests merged in 2024-02, with the labels that each got.

#3603 Add main mlpack documentation framework
  doc/citation.md
  doc/developer/version.md
  doc/index.md
  doc/user/core.md
  doc/user/load_save.md
  doc/user/matrices.md
  src/mlpack/core/kernels/epanechnikov_kernel.hpp
  src/mlpack/core/kernels/epanechnikov_kernel_impl.hpp
  src/mlpack/core/kernels/example_kernel.hpp
  src/mlpack/core/kernels/gaussian_kernel.hpp
  src/mlpack/core/kernels/spherical_kernel.hpp
  src/mlpack/tests/kernel_test.cpp
Labels: c: documentation, t: added feature

#3626 [R] Add an inline plugin for R
  HISTORY.md
  src/mlpack/bindings/R/mlpack/R/inline.R
Labels: s: unanswered, s: unlabeled

#3627 [R] Remove extra gcc-specific options from Makevars.win
  src/mlpack/bindings/R/mlpack/src/Makevars.win
Labels: c: build system, c: automatic bindings, t: bugfix

#3615 Document `core/math/`
  doc/user/core.md
  src/mlpack/core/data/load_image_impl.hpp
  src/mlpack/core/data/scaler_methods/pca_whitening.hpp
  src/mlpack/core/data/scaler_methods/zca_whitening.hpp
  src/mlpack/core/math/ccov.hpp
  src/mlpack/core/math/ccov_impl.hpp
  src/mlpack/core/math/clamp.hpp
  src/mlpack/core/math/columns_to_blocks.hpp
  src/mlpack/core/math/columns_to_blocks_impl.hpp
  src/mlpack/core/math/digamma.hpp
  src/mlpack/core/math/lin_alg.hpp
  src/mlpack/core/math/lin_alg_impl.hpp
  src/mlpack/core/math/log_add_impl.hpp
  src/mlpack/core/math/math.hpp
  src/mlpack/core/math/quantile.hpp
  src/mlpack/core/math/rand_vector.hpp
  src/mlpack/core/math/random.hpp
  src/mlpack/core/tree/ballbound_impl.hpp
  src/mlpack/core/tree/binary_space_tree/rp_tree_max_split_impl.hpp
  src/mlpack/core/tree/binary_space_tree/rp_tree_mean_split.hpp
  src/mlpack/core/tree/binary_space_tree/rp_tree_mean_split_impl.hpp
  src/mlpack/core/tree/binary_space_tree/vantage_point_split_impl.hpp
  src/mlpack/core/tree/hollow_ball_bound_impl.hpp
  src/mlpack/methods/kernel_pca/kernel_rules/nystroem_method.hpp
  src/mlpack/methods/local_coordinate_coding/lcc_impl.hpp
  src/mlpack/methods/pca/pca_impl.hpp
  src/mlpack/methods/rann/ra_search_impl.hpp
  src/mlpack/methods/rann/ra_search_rules_impl.hpp
  src/mlpack/methods/reinforcement_learning/environment/acrobot.hpp
  src/mlpack/methods/reinforcement_learning/environment/continuous_mountain_car.hpp
  src/mlpack/methods/reinforcement_learning/environment/mountain_car.hpp
  src/mlpack/methods/reinforcement_learning/environment/pendulum.hpp
  src/mlpack/methods/reinforcement_learning/environment/reward_clipping.hpp
  src/mlpack/methods/sparse_coding/sparse_coding_impl.hpp
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/block_krylov_svd_test.cpp
  src/mlpack/tests/lin_alg_test.cpp
  src/mlpack/tests/randomized_svd_test.cpp
Labels: c: core, c: documentation, t: added feature

#3636 [R] Update roxygen2 package-level documentation entry
  HISTORY.md
  src/mlpack/bindings/R/mlpack/R/package.R
Labels: s: unanswered, s: unlabeled
