Repository mlpack/mlpack, pull requests merged in 2024-04, with the labels that each got.

#3674 DecisionTree documentation - NoRecursion flag
  doc/user/methods/decision_tree.md
  doc/user/methods/decision_tree_regressor.md
Labels: c: documentation, t: bugfix

#3670 Add Warning for Ubuntu LTS installation instructions
  doc/quickstart/cpp.md
Labels: s: unanswered, s: unlabeled

#3673 Corrected the example code for python bindings quick starter
  doc/quickstart/python.md
Labels: c: automatic bindings, c: documentation, t: bugfix

#3678 Add more links to sidebar, including CV/HPT.
  doc/index.md
  doc/sidebar.html
Labels: c: documentation

#3679 Fix batch handling for `Add::Gradient()`
  src/mlpack/methods/ann/layer/add_impl.hpp
  src/mlpack/tests/ann/layer/add.cpp
  src/mlpack/tests/ann/layer_test.cpp
Labels: c: methods, t: bugfix

#3689 Fix `AdaBoost` constructor parameter table
  doc/user/methods/adaboost.md
Labels: c: documentation, t: bugfix

#3691 Fix `verbose` for R bindings
  HISTORY.md
  src/mlpack/bindings/R/mlpack/src/rcpp_mlpack.h
  src/mlpack/bindings/R/print_R.cpp
  src/mlpack/bindings/R/r_method.cpp.in
Labels: c: automatic bindings, t: bugfix

#3635 Attempt to fix Windows build
  .ci/ci.yaml
  .ci/macos-steps.yaml
  .ci/windows-steps.yaml
  CMake/cotire.cmake
  CMakeLists.txt
  HISTORY.md
  src/mlpack/methods/det/dtree.hpp
  src/mlpack/methods/nca/nca_main.cpp
  src/mlpack/tests/CMakeLists.txt
  src/mlpack/tests/det_test.cpp
  src/mlpack/tests/hpt_test.cpp
Labels: c: build system, t: bugfix

#3688 Documentation for `NMF` plus some bugfixes
  doc/index.md
  doc/sidebar.html
  doc/user/load_save.md
  doc/user/methods/nmf.md
  scripts/build-docs.sh
  src/mlpack/core/data/detect_file_type.hpp
  src/mlpack/core/data/detect_file_type_impl.hpp
  src/mlpack/core/data/load.hpp
  src/mlpack/core/data/load_impl.hpp
  src/mlpack/core/data/types_impl.hpp
  src/mlpack/methods/amf/amf.hpp
  src/mlpack/methods/amf/amf_impl.hpp
  src/mlpack/methods/amf/init_rules/average_init.hpp
  src/mlpack/methods/amf/init_rules/given_init.hpp
  src/mlpack/methods/amf/init_rules/init_rules.hpp
  src/mlpack/methods/amf/init_rules/merge_init.hpp
  src/mlpack/methods/amf/init_rules/no_init.hpp
  src/mlpack/methods/amf/init_rules/random_acol_init.hpp
  src/mlpack/methods/amf/init_rules/random_init.hpp
  src/mlpack/methods/amf/termination_policies/max_iteration_termination.hpp
  src/mlpack/methods/amf/termination_policies/simple_residue_termination.hpp
  src/mlpack/methods/amf/termination_policies/simple_tolerance_termination.hpp
  src/mlpack/methods/amf/termination_policies/validation_rmse_termination.hpp
  src/mlpack/methods/amf/update_rules/nmf_als.hpp
  src/mlpack/methods/amf/update_rules/nmf_mult_dist.hpp
  src/mlpack/methods/amf/update_rules/nmf_mult_div.hpp
  src/mlpack/methods/nmf/nmf_main.cpp
  src/mlpack/tests/load_save_test.cpp
  src/mlpack/tests/nmf_test.cpp
Labels: s: unlabeled

#3697 docs: Add Conan Installation steps (quickstart)
  doc/quickstart/cpp.md
Labels: s: unanswered, s: unlabeled

#3694 Test "verbose" option for R.
  src/mlpack/bindings/R/mlpack/tests/testthat/test-R_binding.R
  src/mlpack/bindings/R/tests/test_r_binding_main.cpp
Labels: c: automatic bindings, c: testing, t: added feature
